// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/agent_master/yagpcc_get_service.proto

package greenplum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetGPInfo_GetGPSessions_FullMethodName        = "/yagpcc.GetGPInfo/GetGPSessions"
	GetGPInfo_GetGPQuery_FullMethodName           = "/yagpcc.GetGPInfo/GetGPQuery"
	GetGPInfo_GetGPQueries_FullMethodName         = "/yagpcc.GetGPInfo/GetGPQueries"
	GetGPInfo_GetGPSession_FullMethodName         = "/yagpcc.GetGPInfo/GetGPSession"
	GetGPInfo_GetTotalSessionsStat_FullMethodName = "/yagpcc.GetGPInfo/GetTotalSessionsStat"
)

// GetGPInfoClient is the client API for GetGPInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetGPInfoClient interface {
	GetGPSessions(ctx context.Context, in *GetGPSessionsReq, opts ...grpc.CallOption) (*GetGPSessionsResponse, error)
	GetGPQuery(ctx context.Context, in *GetGPQueryReq, opts ...grpc.CallOption) (*GetGPQueryResponse, error)
	GetGPQueries(ctx context.Context, in *GetGPQueriesReq, opts ...grpc.CallOption) (*GetGPSessionsResponse, error)
	GetGPSession(ctx context.Context, in *GetGPSessionReq, opts ...grpc.CallOption) (*GetGPSessionResponse, error)
	GetTotalSessionsStat(ctx context.Context, in *GetTotalSessionsReq, opts ...grpc.CallOption) (*GetTotalSessionsResponse, error)
}

type getGPInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewGetGPInfoClient(cc grpc.ClientConnInterface) GetGPInfoClient {
	return &getGPInfoClient{cc}
}

func (c *getGPInfoClient) GetGPSessions(ctx context.Context, in *GetGPSessionsReq, opts ...grpc.CallOption) (*GetGPSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGPSessionsResponse)
	err := c.cc.Invoke(ctx, GetGPInfo_GetGPSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getGPInfoClient) GetGPQuery(ctx context.Context, in *GetGPQueryReq, opts ...grpc.CallOption) (*GetGPQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGPQueryResponse)
	err := c.cc.Invoke(ctx, GetGPInfo_GetGPQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getGPInfoClient) GetGPQueries(ctx context.Context, in *GetGPQueriesReq, opts ...grpc.CallOption) (*GetGPSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGPSessionsResponse)
	err := c.cc.Invoke(ctx, GetGPInfo_GetGPQueries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getGPInfoClient) GetGPSession(ctx context.Context, in *GetGPSessionReq, opts ...grpc.CallOption) (*GetGPSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGPSessionResponse)
	err := c.cc.Invoke(ctx, GetGPInfo_GetGPSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getGPInfoClient) GetTotalSessionsStat(ctx context.Context, in *GetTotalSessionsReq, opts ...grpc.CallOption) (*GetTotalSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTotalSessionsResponse)
	err := c.cc.Invoke(ctx, GetGPInfo_GetTotalSessionsStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetGPInfoServer is the server API for GetGPInfo service.
// All implementations must embed UnimplementedGetGPInfoServer
// for forward compatibility.
type GetGPInfoServer interface {
	GetGPSessions(context.Context, *GetGPSessionsReq) (*GetGPSessionsResponse, error)
	GetGPQuery(context.Context, *GetGPQueryReq) (*GetGPQueryResponse, error)
	GetGPQueries(context.Context, *GetGPQueriesReq) (*GetGPSessionsResponse, error)
	GetGPSession(context.Context, *GetGPSessionReq) (*GetGPSessionResponse, error)
	GetTotalSessionsStat(context.Context, *GetTotalSessionsReq) (*GetTotalSessionsResponse, error)
	mustEmbedUnimplementedGetGPInfoServer()
}

// UnimplementedGetGPInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetGPInfoServer struct{}

func (UnimplementedGetGPInfoServer) GetGPSessions(context.Context, *GetGPSessionsReq) (*GetGPSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGPSessions not implemented")
}
func (UnimplementedGetGPInfoServer) GetGPQuery(context.Context, *GetGPQueryReq) (*GetGPQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGPQuery not implemented")
}
func (UnimplementedGetGPInfoServer) GetGPQueries(context.Context, *GetGPQueriesReq) (*GetGPSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGPQueries not implemented")
}
func (UnimplementedGetGPInfoServer) GetGPSession(context.Context, *GetGPSessionReq) (*GetGPSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGPSession not implemented")
}
func (UnimplementedGetGPInfoServer) GetTotalSessionsStat(context.Context, *GetTotalSessionsReq) (*GetTotalSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTotalSessionsStat not implemented")
}
func (UnimplementedGetGPInfoServer) mustEmbedUnimplementedGetGPInfoServer() {}
func (UnimplementedGetGPInfoServer) testEmbeddedByValue()                   {}

// UnsafeGetGPInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetGPInfoServer will
// result in compilation errors.
type UnsafeGetGPInfoServer interface {
	mustEmbedUnimplementedGetGPInfoServer()
}

func RegisterGetGPInfoServer(s grpc.ServiceRegistrar, srv GetGPInfoServer) {
	// If the following call panics, it indicates UnimplementedGetGPInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetGPInfo_ServiceDesc, srv)
}

func _GetGPInfo_GetGPSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGPSessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetGPInfoServer).GetGPSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetGPInfo_GetGPSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetGPInfoServer).GetGPSessions(ctx, req.(*GetGPSessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GetGPInfo_GetGPQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGPQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetGPInfoServer).GetGPQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetGPInfo_GetGPQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetGPInfoServer).GetGPQuery(ctx, req.(*GetGPQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GetGPInfo_GetGPQueries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGPQueriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetGPInfoServer).GetGPQueries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetGPInfo_GetGPQueries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetGPInfoServer).GetGPQueries(ctx, req.(*GetGPQueriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GetGPInfo_GetGPSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGPSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetGPInfoServer).GetGPSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetGPInfo_GetGPSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetGPInfoServer).GetGPSession(ctx, req.(*GetGPSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GetGPInfo_GetTotalSessionsStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTotalSessionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetGPInfoServer).GetTotalSessionsStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetGPInfo_GetTotalSessionsStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetGPInfoServer).GetTotalSessionsStat(ctx, req.(*GetTotalSessionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GetGPInfo_ServiceDesc is the grpc.ServiceDesc for GetGPInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetGPInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yagpcc.GetGPInfo",
	HandlerType: (*GetGPInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGPSessions",
			Handler:    _GetGPInfo_GetGPSessions_Handler,
		},
		{
			MethodName: "GetGPQuery",
			Handler:    _GetGPInfo_GetGPQuery_Handler,
		},
		{
			MethodName: "GetGPQueries",
			Handler:    _GetGPInfo_GetGPQueries_Handler,
		},
		{
			MethodName: "GetGPSession",
			Handler:    _GetGPInfo_GetGPSession_Handler,
		},
		{
			MethodName: "GetTotalSessionsStat",
			Handler:    _GetGPInfo_GetTotalSessionsStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/agent_master/yagpcc_get_service.proto",
}
