// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/agent_master/yagpcc_action_service.proto

package greenplum

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	common "github.com/open-gpdb/yagpcc/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerminateResponseStatusCode int32

const (
	TerminateResponseStatusCode_TERMINATE_RESPONSE_STATUS_CODE_UNSPECIFIED TerminateResponseStatusCode = 0
	TerminateResponseStatusCode_TERMINATE_RESPONSE_STATUS_CODE_SUCCESS     TerminateResponseStatusCode = 1
	TerminateResponseStatusCode_TERMINATE_RESPONSE_STATUS_CODE_ERROR       TerminateResponseStatusCode = 2
)

// Enum value maps for TerminateResponseStatusCode.
var (
	TerminateResponseStatusCode_name = map[int32]string{
		0: "TERMINATE_RESPONSE_STATUS_CODE_UNSPECIFIED",
		1: "TERMINATE_RESPONSE_STATUS_CODE_SUCCESS",
		2: "TERMINATE_RESPONSE_STATUS_CODE_ERROR",
	}
	TerminateResponseStatusCode_value = map[string]int32{
		"TERMINATE_RESPONSE_STATUS_CODE_UNSPECIFIED": 0,
		"TERMINATE_RESPONSE_STATUS_CODE_SUCCESS":     1,
		"TERMINATE_RESPONSE_STATUS_CODE_ERROR":       2,
	}
)

func (x TerminateResponseStatusCode) Enum() *TerminateResponseStatusCode {
	p := new(TerminateResponseStatusCode)
	*p = x
	return p
}

func (x TerminateResponseStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminateResponseStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_agent_master_yagpcc_action_service_proto_enumTypes[0].Descriptor()
}

func (TerminateResponseStatusCode) Type() protoreflect.EnumType {
	return &file_api_proto_agent_master_yagpcc_action_service_proto_enumTypes[0]
}

func (x TerminateResponseStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminateResponseStatusCode.Descriptor instead.
func (TerminateResponseStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_agent_master_yagpcc_action_service_proto_rawDescGZIP(), []int{0}
}

type MoveQueryToResourceGroupRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueryKey          *common.QueryKey       `protobuf:"bytes,1,opt,name=query_key,json=queryKey,proto3" json:"query_key,omitempty"`
	ResourceGroupName string                 `protobuf:"bytes,2,opt,name=resource_group_name,json=resourceGroupName,proto3" json:"resource_group_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MoveQueryToResourceGroupRequest) Reset() {
	*x = MoveQueryToResourceGroupRequest{}
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveQueryToResourceGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveQueryToResourceGroupRequest) ProtoMessage() {}

func (x *MoveQueryToResourceGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveQueryToResourceGroupRequest.ProtoReflect.Descriptor instead.
func (*MoveQueryToResourceGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_master_yagpcc_action_service_proto_rawDescGZIP(), []int{0}
}

func (x *MoveQueryToResourceGroupRequest) GetQueryKey() *common.QueryKey {
	if x != nil {
		return x.QueryKey
	}
	return nil
}

func (x *MoveQueryToResourceGroupRequest) GetResourceGroupName() string {
	if x != nil {
		return x.ResourceGroupName
	}
	return ""
}

type TerminateQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryKey      *common.QueryKey       `protobuf:"bytes,1,opt,name=query_key,json=queryKey,proto3" json:"query_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateQueryRequest) Reset() {
	*x = TerminateQueryRequest{}
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateQueryRequest) ProtoMessage() {}

func (x *TerminateQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateQueryRequest.ProtoReflect.Descriptor instead.
func (*TerminateQueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_master_yagpcc_action_service_proto_rawDescGZIP(), []int{1}
}

func (x *TerminateQueryRequest) GetQueryKey() *common.QueryKey {
	if x != nil {
		return x.QueryKey
	}
	return nil
}

type TerminateResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	StatusCode    TerminateResponseStatusCode `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3,enum=yagpcc.TerminateResponseStatusCode" json:"status_code,omitempty"`
	StatusText    string                      `protobuf:"bytes,2,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateResponse) Reset() {
	*x = TerminateResponse{}
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponse) ProtoMessage() {}

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_master_yagpcc_action_service_proto_rawDescGZIP(), []int{2}
}

func (x *TerminateResponse) GetStatusCode() TerminateResponseStatusCode {
	if x != nil {
		return x.StatusCode
	}
	return TerminateResponseStatusCode_TERMINATE_RESPONSE_STATUS_CODE_UNSPECIFIED
}

func (x *TerminateResponse) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

type TerminateResponses struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TerminateResponse []*TerminateResponse   `protobuf:"bytes,1,rep,name=terminate_response,json=terminateResponse,proto3" json:"terminate_response,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TerminateResponses) Reset() {
	*x = TerminateResponses{}
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateResponses) ProtoMessage() {}

func (x *TerminateResponses) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateResponses.ProtoReflect.Descriptor instead.
func (*TerminateResponses) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_master_yagpcc_action_service_proto_rawDescGZIP(), []int{3}
}

func (x *TerminateResponses) GetTerminateResponse() []*TerminateResponse {
	if x != nil {
		return x.TerminateResponse
	}
	return nil
}

type TerminateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    *common.SessionKey     `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionRequest) Reset() {
	*x = TerminateSessionRequest{}
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionRequest) ProtoMessage() {}

func (x *TerminateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionRequest.ProtoReflect.Descriptor instead.
func (*TerminateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_master_yagpcc_action_service_proto_rawDescGZIP(), []int{4}
}

func (x *TerminateSessionRequest) GetSessionKey() *common.SessionKey {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

type TerminateSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	QueryId       uint64                 `protobuf:"varint,3,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionsRequest) Reset() {
	*x = TerminateSessionsRequest{}
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionsRequest) ProtoMessage() {}

func (x *TerminateSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionsRequest.ProtoReflect.Descriptor instead.
func (*TerminateSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_master_yagpcc_action_service_proto_rawDescGZIP(), []int{5}
}

func (x *TerminateSessionsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *TerminateSessionsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TerminateSessionsRequest) GetQueryId() uint64 {
	if x != nil {
		return x.QueryId
	}
	return 0
}

var File_api_proto_agent_master_yagpcc_action_service_proto protoreflect.FileDescriptor

const file_api_proto_agent_master_yagpcc_action_service_proto_rawDesc = "" +
	"\n" +
	"2api/proto/agent_master/yagpcc_action_service.proto\x12\x06yagpcc\x1a\x1bgoogle/protobuf/empty.proto\x1a%api/proto/common/yagpcc_metrics.proto\x1a%api/proto/common/yagpcc_session.proto\"\x80\x01\n" +
	"\x1fMoveQueryToResourceGroupRequest\x12-\n" +
	"\tquery_key\x18\x01 \x01(\v2\x10.yagpcc.QueryKeyR\bqueryKey\x12.\n" +
	"\x13resource_group_name\x18\x02 \x01(\tR\x11resourceGroupName\"F\n" +
	"\x15TerminateQueryRequest\x12-\n" +
	"\tquery_key\x18\x01 \x01(\v2\x10.yagpcc.QueryKeyR\bqueryKey\"z\n" +
	"\x11TerminateResponse\x12D\n" +
	"\vstatus_code\x18\x01 \x01(\x0e2#.yagpcc.TerminateResponseStatusCodeR\n" +
	"statusCode\x12\x1f\n" +
	"\vstatus_text\x18\x02 \x01(\tR\n" +
	"statusText\"^\n" +
	"\x12TerminateResponses\x12H\n" +
	"\x12terminate_response\x18\x01 \x03(\v2\x19.yagpcc.TerminateResponseR\x11terminateResponse\"N\n" +
	"\x17TerminateSessionRequest\x123\n" +
	"\vsession_key\x18\x01 \x01(\v2\x12.yagpcc.SessionKeyR\n" +
	"sessionKey\"m\n" +
	"\x18TerminateSessionsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x19\n" +
	"\bquery_id\x18\x03 \x01(\x04R\aqueryId*\xa3\x01\n" +
	"\x1bTerminateResponseStatusCode\x12.\n" +
	"*TERMINATE_RESPONSE_STATUS_CODE_UNSPECIFIED\x10\x00\x12*\n" +
	"&TERMINATE_RESPONSE_STATUS_CODE_SUCCESS\x10\x01\x12(\n" +
	"$TERMINATE_RESPONSE_STATUS_CODE_ERROR\x10\x022\xdb\x02\n" +
	"\rActionService\x12[\n" +
	"\x18MoveQueryToResourceGroup\x12'.yagpcc.MoveQueryToResourceGroupRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0eTerminateQuery\x12\x1d.yagpcc.TerminateQueryRequest\x1a\x19.yagpcc.TerminateResponse\x12N\n" +
	"\x10TerminateSession\x12\x1f.yagpcc.TerminateSessionRequest\x1a\x19.yagpcc.TerminateResponse\x12Q\n" +
	"\x11TerminateSessions\x12 .yagpcc.TerminateSessionsRequest\x1a\x1a.yagpcc.TerminateResponsesBNB\x0eMasterYAGPCCAAZ<github.com/open-gpdb/yagpcc/api/proto/agent_master;greenplumb\x06proto3"

var (
	file_api_proto_agent_master_yagpcc_action_service_proto_rawDescOnce sync.Once
	file_api_proto_agent_master_yagpcc_action_service_proto_rawDescData []byte
)

func file_api_proto_agent_master_yagpcc_action_service_proto_rawDescGZIP() []byte {
	file_api_proto_agent_master_yagpcc_action_service_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_master_yagpcc_action_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_master_yagpcc_action_service_proto_rawDesc), len(file_api_proto_agent_master_yagpcc_action_service_proto_rawDesc)))
	})
	return file_api_proto_agent_master_yagpcc_action_service_proto_rawDescData
}

var file_api_proto_agent_master_yagpcc_action_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_agent_master_yagpcc_action_service_proto_goTypes = []any{
	(TerminateResponseStatusCode)(0),        // 0: yagpcc.TerminateResponseStatusCode
	(*MoveQueryToResourceGroupRequest)(nil), // 1: yagpcc.MoveQueryToResourceGroupRequest
	(*TerminateQueryRequest)(nil),           // 2: yagpcc.TerminateQueryRequest
	(*TerminateResponse)(nil),               // 3: yagpcc.TerminateResponse
	(*TerminateResponses)(nil),              // 4: yagpcc.TerminateResponses
	(*TerminateSessionRequest)(nil),         // 5: yagpcc.TerminateSessionRequest
	(*TerminateSessionsRequest)(nil),        // 6: yagpcc.TerminateSessionsRequest
	(*common.QueryKey)(nil),                 // 7: yagpcc.QueryKey
	(*common.SessionKey)(nil),               // 8: yagpcc.SessionKey
	(*empty.Empty)(nil),                     // 9: google.protobuf.Empty
}
var file_api_proto_agent_master_yagpcc_action_service_proto_depIdxs = []int32{
	7, // 0: yagpcc.MoveQueryToResourceGroupRequest.query_key:type_name -> yagpcc.QueryKey
	7, // 1: yagpcc.TerminateQueryRequest.query_key:type_name -> yagpcc.QueryKey
	0, // 2: yagpcc.TerminateResponse.status_code:type_name -> yagpcc.TerminateResponseStatusCode
	3, // 3: yagpcc.TerminateResponses.terminate_response:type_name -> yagpcc.TerminateResponse
	8, // 4: yagpcc.TerminateSessionRequest.session_key:type_name -> yagpcc.SessionKey
	1, // 5: yagpcc.ActionService.MoveQueryToResourceGroup:input_type -> yagpcc.MoveQueryToResourceGroupRequest
	2, // 6: yagpcc.ActionService.TerminateQuery:input_type -> yagpcc.TerminateQueryRequest
	5, // 7: yagpcc.ActionService.TerminateSession:input_type -> yagpcc.TerminateSessionRequest
	6, // 8: yagpcc.ActionService.TerminateSessions:input_type -> yagpcc.TerminateSessionsRequest
	9, // 9: yagpcc.ActionService.MoveQueryToResourceGroup:output_type -> google.protobuf.Empty
	3, // 10: yagpcc.ActionService.TerminateQuery:output_type -> yagpcc.TerminateResponse
	3, // 11: yagpcc.ActionService.TerminateSession:output_type -> yagpcc.TerminateResponse
	4, // 12: yagpcc.ActionService.TerminateSessions:output_type -> yagpcc.TerminateResponses
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_agent_master_yagpcc_action_service_proto_init() }
func file_api_proto_agent_master_yagpcc_action_service_proto_init() {
	if File_api_proto_agent_master_yagpcc_action_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_master_yagpcc_action_service_proto_rawDesc), len(file_api_proto_agent_master_yagpcc_action_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_master_yagpcc_action_service_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_master_yagpcc_action_service_proto_depIdxs,
		EnumInfos:         file_api_proto_agent_master_yagpcc_action_service_proto_enumTypes,
		MessageInfos:      file_api_proto_agent_master_yagpcc_action_service_proto_msgTypes,
	}.Build()
	File_api_proto_agent_master_yagpcc_action_service_proto = out.File
	file_api_proto_agent_master_yagpcc_action_service_proto_goTypes = nil
	file_api_proto_agent_master_yagpcc_action_service_proto_depIdxs = nil
}
