// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/common/yagpcc_metrics.proto

package greenplum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryStatus int32

const (
	QueryStatus_QUERY_STATUS_UNSPECIFIED QueryStatus = 0
	QueryStatus_QUERY_STATUS_SUBMIT      QueryStatus = 1
	QueryStatus_QUERY_STATUS_START       QueryStatus = 2
	QueryStatus_QUERY_STATUS_DONE        QueryStatus = 3
	QueryStatus_QUERY_STATUS_QUERY_DONE  QueryStatus = 4
	QueryStatus_QUERY_STATUS_ERROR       QueryStatus = 5
	QueryStatus_QUERY_STATUS_CANCELLING  QueryStatus = 6
	QueryStatus_QUERY_STATUS_CANCELED    QueryStatus = 7
	QueryStatus_QUERY_STATUS_END         QueryStatus = 8
)

// Enum value maps for QueryStatus.
var (
	QueryStatus_name = map[int32]string{
		0: "QUERY_STATUS_UNSPECIFIED",
		1: "QUERY_STATUS_SUBMIT",
		2: "QUERY_STATUS_START",
		3: "QUERY_STATUS_DONE",
		4: "QUERY_STATUS_QUERY_DONE",
		5: "QUERY_STATUS_ERROR",
		6: "QUERY_STATUS_CANCELLING",
		7: "QUERY_STATUS_CANCELED",
		8: "QUERY_STATUS_END",
	}
	QueryStatus_value = map[string]int32{
		"QUERY_STATUS_UNSPECIFIED": 0,
		"QUERY_STATUS_SUBMIT":      1,
		"QUERY_STATUS_START":       2,
		"QUERY_STATUS_DONE":        3,
		"QUERY_STATUS_QUERY_DONE":  4,
		"QUERY_STATUS_ERROR":       5,
		"QUERY_STATUS_CANCELLING":  6,
		"QUERY_STATUS_CANCELED":    7,
		"QUERY_STATUS_END":         8,
	}
)

func (x QueryStatus) Enum() *QueryStatus {
	p := new(QueryStatus)
	*p = x
	return p
}

func (x QueryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_yagpcc_metrics_proto_enumTypes[0].Descriptor()
}

func (QueryStatus) Type() protoreflect.EnumType {
	return &file_api_proto_common_yagpcc_metrics_proto_enumTypes[0]
}

func (x QueryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryStatus.Descriptor instead.
func (QueryStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{0}
}

type PlanGenerator int32

const (
	// PLAN_GENERATOR_UNSPECIFIED: the generator value is unknown or not set.
	PlanGenerator_PLAN_GENERATOR_UNSPECIFIED PlanGenerator = 0
	// PLAN_GENERATOR_PLANNER: the query plan was generated by the postgres legacy optimizer.
	PlanGenerator_PLAN_GENERATOR_PLANNER PlanGenerator = 1
	// PLAN_GENERATOR_OPTIMIZER: the query plan was generated by the GPORCA.
	PlanGenerator_PLAN_GENERATOR_OPTIMIZER PlanGenerator = 2
)

// Enum value maps for PlanGenerator.
var (
	PlanGenerator_name = map[int32]string{
		0: "PLAN_GENERATOR_UNSPECIFIED",
		1: "PLAN_GENERATOR_PLANNER",
		2: "PLAN_GENERATOR_OPTIMIZER",
	}
	PlanGenerator_value = map[string]int32{
		"PLAN_GENERATOR_UNSPECIFIED": 0,
		"PLAN_GENERATOR_PLANNER":     1,
		"PLAN_GENERATOR_OPTIMIZER":   2,
	}
)

func (x PlanGenerator) Enum() *PlanGenerator {
	p := new(PlanGenerator)
	*p = x
	return p
}

func (x PlanGenerator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanGenerator) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_common_yagpcc_metrics_proto_enumTypes[1].Descriptor()
}

func (PlanGenerator) Type() protoreflect.EnumType {
	return &file_api_proto_common_yagpcc_metrics_proto_enumTypes[1]
}

func (x PlanGenerator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanGenerator.Descriptor instead.
func (PlanGenerator) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{1}
}

// QueryInfo: various attributes of the query.
type QueryInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// generator: indicates plan generator used for query: GPORCA/postgres legacy optimizer.
	Generator PlanGenerator `protobuf:"varint,1,opt,name=generator,proto3,enum=yagpcc.PlanGenerator" json:"generator,omitempty"`
	// query_id: normalized query hash value.
	QueryId uint64 `protobuf:"varint,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	// plan_id: normalized plan hash value.
	PlanId uint64 `protobuf:"varint,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	// query_text: query raw text.
	QueryText string `protobuf:"bytes,4,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	// plan_text: plan raw text.
	PlanText string `protobuf:"bytes,5,opt,name=plan_text,json=planText,proto3" json:"plan_text,omitempty"`
	// template_query_text: normalized query text.
	// Deprecated: unused.
	//
	// Deprecated: Marked as deprecated in api/proto/common/yagpcc_metrics.proto.
	TemplateQueryText string `protobuf:"bytes,6,opt,name=template_query_text,json=templateQueryText,proto3" json:"template_query_text,omitempty"`
	// template_plan_text: normalized plan text.
	// Deprecated: unused.
	//
	// Deprecated: Marked as deprecated in api/proto/common/yagpcc_metrics.proto.
	TemplatePlanText string `protobuf:"bytes,7,opt,name=template_plan_text,json=templatePlanText,proto3" json:"template_plan_text,omitempty"`
	// userName: name of the user executing query.
	UserName string `protobuf:"bytes,8,opt,name=userName,proto3" json:"userName,omitempty"`
	// databaseName: name of the database where query is executing.
	DatabaseName string `protobuf:"bytes,9,opt,name=databaseName,proto3" json:"databaseName,omitempty"`
	// rsgname: name of the resource group where query is executing.
	Rsgname string `protobuf:"bytes,10,opt,name=rsgname,proto3" json:"rsgname,omitempty"`
	// analyze_text: explain analyze in text format.
	AnalyzeText string `protobuf:"bytes,11,opt,name=analyze_text,json=analyzeText,proto3" json:"analyze_text,omitempty"`
	// submit time: time when query was submitted
	SubmitTime *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	// start time: time when query started execution
	StartTime *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// end time: time when query finished
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryInfo) Reset() {
	*x = QueryInfo{}
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInfo) ProtoMessage() {}

func (x *QueryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInfo.ProtoReflect.Descriptor instead.
func (*QueryInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *QueryInfo) GetGenerator() PlanGenerator {
	if x != nil {
		return x.Generator
	}
	return PlanGenerator_PLAN_GENERATOR_UNSPECIFIED
}

func (x *QueryInfo) GetQueryId() uint64 {
	if x != nil {
		return x.QueryId
	}
	return 0
}

func (x *QueryInfo) GetPlanId() uint64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *QueryInfo) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *QueryInfo) GetPlanText() string {
	if x != nil {
		return x.PlanText
	}
	return ""
}

// Deprecated: Marked as deprecated in api/proto/common/yagpcc_metrics.proto.
func (x *QueryInfo) GetTemplateQueryText() string {
	if x != nil {
		return x.TemplateQueryText
	}
	return ""
}

// Deprecated: Marked as deprecated in api/proto/common/yagpcc_metrics.proto.
func (x *QueryInfo) GetTemplatePlanText() string {
	if x != nil {
		return x.TemplatePlanText
	}
	return ""
}

func (x *QueryInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *QueryInfo) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *QueryInfo) GetRsgname() string {
	if x != nil {
		return x.Rsgname
	}
	return ""
}

func (x *QueryInfo) GetAnalyzeText() string {
	if x != nil {
		return x.AnalyzeText
	}
	return ""
}

func (x *QueryInfo) GetSubmitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmitTime
	}
	return nil
}

func (x *QueryInfo) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryInfo) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type AdditionalQueryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NestedLevel   int64                  `protobuf:"varint,1,opt,name=nested_level,json=nestedLevel,proto3" json:"nested_level,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SliceId       int64                  `protobuf:"varint,3,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdditionalQueryInfo) Reset() {
	*x = AdditionalQueryInfo{}
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdditionalQueryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalQueryInfo) ProtoMessage() {}

func (x *AdditionalQueryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalQueryInfo.ProtoReflect.Descriptor instead.
func (*AdditionalQueryInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *AdditionalQueryInfo) GetNestedLevel() int64 {
	if x != nil {
		return x.NestedLevel
	}
	return 0
}

func (x *AdditionalQueryInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AdditionalQueryInfo) GetSliceId() int64 {
	if x != nil {
		return x.SliceId
	}
	return 0
}

type AdditionalQueryStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdditionalQueryStat) Reset() {
	*x = AdditionalQueryStat{}
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdditionalQueryStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalQueryStat) ProtoMessage() {}

func (x *AdditionalQueryStat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalQueryStat.ProtoReflect.Descriptor instead.
func (*AdditionalQueryStat) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *AdditionalQueryStat) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GPMetrics: collection of system and Greenplum related statistics
// associated with the session or the query (depending on context).
type GPMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// systemStat: statistics collected from procfs for query or session (depending on context)
	SystemStat *SystemStat `protobuf:"bytes,1,opt,name=systemStat,proto3" json:"systemStat,omitempty"`
	// instrumentation: various statistics related to query plan nodes.
	Instrumentation *MetricInstrumentation `protobuf:"bytes,2,opt,name=instrumentation,proto3" json:"instrumentation,omitempty"`
	// spill: detailed statistics about produced spill files
	Spill         *SpillInfo `protobuf:"bytes,3,opt,name=spill,proto3" json:"spill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPMetrics) Reset() {
	*x = GPMetrics{}
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPMetrics) ProtoMessage() {}

func (x *GPMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPMetrics.ProtoReflect.Descriptor instead.
func (*GPMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *GPMetrics) GetSystemStat() *SystemStat {
	if x != nil {
		return x.SystemStat
	}
	return nil
}

func (x *GPMetrics) GetInstrumentation() *MetricInstrumentation {
	if x != nil {
		return x.Instrumentation
	}
	return nil
}

func (x *GPMetrics) GetSpill() *SpillInfo {
	if x != nil {
		return x.Spill
	}
	return nil
}

// QueryKey: compound cluster wide unique query identifier.
type QueryKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tmid: distributed transaction timestamp (as unix timestamp)
	// to ensure QueryKey uniqueness through all cluster lifetime.
	Tmid int32 `protobuf:"varint,1,opt,name=tmid,proto3" json:"tmid,omitempty"`
	// ssid: query session identifier from pg_stat_activity system view.
	Ssid int32 `protobuf:"varint,2,opt,name=ssid,proto3" json:"ssid,omitempty"`
	// ccnt: the command number within this session as shown by gp_command_count.
	// All records associated with the query will have the same ccnt.
	Ccnt          int32 `protobuf:"varint,3,opt,name=ccnt,proto3" json:"ccnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKey) Reset() {
	*x = QueryKey{}
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKey) ProtoMessage() {}

func (x *QueryKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKey.ProtoReflect.Descriptor instead.
func (*QueryKey) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *QueryKey) GetTmid() int32 {
	if x != nil {
		return x.Tmid
	}
	return 0
}

func (x *QueryKey) GetSsid() int32 {
	if x != nil {
		return x.Ssid
	}
	return 0
}

func (x *QueryKey) GetCcnt() int32 {
	if x != nil {
		return x.Ccnt
	}
	return 0
}

// SegmentKey: compound cluster wide segment identifier.
type SegmentKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// dbid: the dbid of this database.
	Dbid int32 `protobuf:"varint,1,opt,name=dbid,proto3" json:"dbid,omitempty"`
	// segindex: content indicator:
	// * -1 for entry database,
	// * 0, ..., n-1 for segment database
	// * a primary and its mirror have the same segIndex.
	Segindex      int32 `protobuf:"varint,2,opt,name=segindex,proto3" json:"segindex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentKey) Reset() {
	*x = SegmentKey{}
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentKey) ProtoMessage() {}

func (x *SegmentKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentKey.ProtoReflect.Descriptor instead.
func (*SegmentKey) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *SegmentKey) GetDbid() int32 {
	if x != nil {
		return x.Dbid
	}
	return 0
}

func (x *SegmentKey) GetSegindex() int32 {
	if x != nil {
		return x.Segindex
	}
	return 0
}

// SystemStat: statistics collected from procfs for query or session (depending on context).
type SystemStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// runningTimeSeconds: sum of userTimeSeconds and kernelTimeSeconds
	// theese value is ignored by yagpcc and calculated using userTimeSeconds and kernelTimeSeconds once again
	//
	// Importance: major
	// Aggregation: sum
	RunningTimeSeconds float64 `protobuf:"fixed64,1,opt,name=runningTimeSeconds,proto3" json:"runningTimeSeconds,omitempty"`
	// userTimeSeconds: total amount of CPU seconds spent in user space
	// by all backend processes associated with query or session.
	//
	// Source: /proc/pid/stat utime
	// Importance: major
	// Aggregation: sum
	UserTimeSeconds float64 `protobuf:"fixed64,2,opt,name=userTimeSeconds,proto3" json:"userTimeSeconds,omitempty"`
	// kernelTimeSeconds: total amount of CPU seconds spent in kernel space
	// by all backend processes associated with query or session.
	//
	// Source: /proc/pid/stat stime
	// Importance: major
	// Aggregation: sum
	KernelTimeSeconds float64 `protobuf:"fixed64,3,opt,name=kernelTimeSeconds,proto3" json:"kernelTimeSeconds,omitempty"`
	// vsize: maximum virtual memory size (in bytes)
	// used by all backend processes associated with the query or session.
	//
	// Source: /proc/pid/stat vsize
	// Importance: major (possibly wrong aggregation algorithm)
	// Aggregation: max
	Vsize uint64 `protobuf:"varint,4,opt,name=vsize,proto3" json:"vsize,omitempty"`
	// rss: max amount of consumed physical memory (RAM)
	// of all backend processes associated with query or session.
	//
	// Source: /proc/pid/stat rss
	// Importance: major (possibly wrong aggregation algorithm)
	// Aggregation: max
	Rss uint64 `protobuf:"varint,5,opt,name=rss,proto3" json:"rss,omitempty"`
	// VmSizeKb: maximum virtual memory size (in kilobytes) currently allocated
	// to all backend processes associated with the query or session.
	//
	// Source: /proc/pid/status VmSize
	// Importance: major (possibly wrong aggregation algorithm)
	// Aggregation: max
	// Deprecated: duplicate of vsize.
	//
	// Deprecated: Marked as deprecated in api/proto/common/yagpcc_metrics.proto.
	VmSizeKb uint64 `protobuf:"varint,6,opt,name=VmSizeKb,proto3" json:"VmSizeKb,omitempty"`
	// VmPeakKb: max peak virtual memory size that the backend process
	// associated with query or session has consumed since its inception.
	//
	// Source: /proc/pid/status VmPeak
	// Importance: major (possibly wrong aggregation algorithm)
	// Aggregation: max
	VmPeakKb uint64 `protobuf:"varint,7,opt,name=VmPeakKb,proto3" json:"VmPeakKb,omitempty"`
	// rchar: total number of characters (bytes) that have been passed to successful read(2)
	// and similar system calls by all of backend processes associated with query or session.
	//
	// Source: /proc/pid/io rchar
	// Importance: normal
	// Aggregation: sum
	Rchar uint64 `protobuf:"varint,8,opt,name=rchar,proto3" json:"rchar,omitempty"`
	// wchar: total number of bytes that a process has passed to system calls like
	// write(), pwrite(), sendfile(), copy_file_range(), and similar functions
	// by all of backend processes associated with query or session.
	//
	// Source: /proc/pid/io wchar
	// Importance: normal
	// Aggregation: sum
	Wchar uint64 `protobuf:"varint,9,opt,name=wchar,proto3" json:"wchar,omitempty"`
	// syscr: total number of "file read" system calls performed
	// by all of backend processes associated with query or session.
	//
	// Source: /proc/pid/io syscr
	// Importance: minor
	// Aggregation: sum
	Syscr uint64 `protobuf:"varint,10,opt,name=syscr,proto3" json:"syscr,omitempty"`
	// syscw: total number of "file write" system calls performed
	// by all of backend processes associated with query or session.
	//
	// Source: /proc/pid/io syscw
	// Importance: minor
	// Aggregation: sum
	Syscw uint64 `protobuf:"varint,11,opt,name=syscw,proto3" json:"syscw,omitempty"`
	// read_bytes: total number of bytes that all of backend processes associated with query or session
	// has really fetched from the storage layer.
	//
	// Source: /proc/pid/io read_bytes
	// Importance: major
	// Aggregation: sum
	ReadBytes uint64 `protobuf:"varint,12,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	// write_bytes: total number of bytes that all of backend processes associated with query or session
	// are really sent to the storage layer.
	// Reflecting actual disk I/O.
	//
	// Source: /proc/pid/io write_bytes
	// Importance: major
	// Aggregation: sum
	WriteBytes uint64 `protobuf:"varint,13,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	// cancelled_write_bytes: total number of bytes that were initially accounted as writes
	// by all of backend processes associated with query or session
	// but were subsequently not written to storage.
	//
	// Source: /proc/pid/io cancelled_write_bytes
	// Importance: minor
	// Aggregation: sum
	CancelledWriteBytes uint64 `protobuf:"varint,14,opt,name=cancelled_write_bytes,json=cancelledWriteBytes,proto3" json:"cancelled_write_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SystemStat) Reset() {
	*x = SystemStat{}
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStat) ProtoMessage() {}

func (x *SystemStat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStat.ProtoReflect.Descriptor instead.
func (*SystemStat) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *SystemStat) GetRunningTimeSeconds() float64 {
	if x != nil {
		return x.RunningTimeSeconds
	}
	return 0
}

func (x *SystemStat) GetUserTimeSeconds() float64 {
	if x != nil {
		return x.UserTimeSeconds
	}
	return 0
}

func (x *SystemStat) GetKernelTimeSeconds() float64 {
	if x != nil {
		return x.KernelTimeSeconds
	}
	return 0
}

func (x *SystemStat) GetVsize() uint64 {
	if x != nil {
		return x.Vsize
	}
	return 0
}

func (x *SystemStat) GetRss() uint64 {
	if x != nil {
		return x.Rss
	}
	return 0
}

// Deprecated: Marked as deprecated in api/proto/common/yagpcc_metrics.proto.
func (x *SystemStat) GetVmSizeKb() uint64 {
	if x != nil {
		return x.VmSizeKb
	}
	return 0
}

func (x *SystemStat) GetVmPeakKb() uint64 {
	if x != nil {
		return x.VmPeakKb
	}
	return 0
}

func (x *SystemStat) GetRchar() uint64 {
	if x != nil {
		return x.Rchar
	}
	return 0
}

func (x *SystemStat) GetWchar() uint64 {
	if x != nil {
		return x.Wchar
	}
	return 0
}

func (x *SystemStat) GetSyscr() uint64 {
	if x != nil {
		return x.Syscr
	}
	return 0
}

func (x *SystemStat) GetSyscw() uint64 {
	if x != nil {
		return x.Syscw
	}
	return 0
}

func (x *SystemStat) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *SystemStat) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *SystemStat) GetCancelledWriteBytes() uint64 {
	if x != nil {
		return x.CancelledWriteBytes
	}
	return 0
}

// NetworkStat: basic network statistics for all of backend processes
// associated with query or session sent/received to/from the network layer depending on the context.
type NetworkStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total_bytes: total number of bytes (including headers) that all of backend processes
	// associated with query or session sent/received to/from the network layer.
	//
	// Importance: major
	// Aggregation: sum
	TotalBytes uint32 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// tuple_bytes: total number of tuples only bytes (without headers) that all of backend processes
	// associated with query or session sent/received to/from the network layer.
	//
	// Importance: minor
	// Aggregation: sum
	TupleBytes uint32 `protobuf:"varint,2,opt,name=tuple_bytes,json=tupleBytes,proto3" json:"tuple_bytes,omitempty"`
	// chunks: total number of chunks (tuples only) that all of backend processes
	// associated with query or session sent/received to/from the network layer.
	//
	// Importance: normal
	// Aggregation: sum
	Chunks uint32 `protobuf:"varint,3,opt,name=chunks,proto3" json:"chunks,omitempty"`
	// the stats here is the same except uses uint64, uint32 is too snal for aggregated stat
	TotalBytesLong uint64 `protobuf:"varint,4,opt,name=total_bytes_long,json=totalBytesLong,proto3" json:"total_bytes_long,omitempty"`
	TupleBytesLong uint64 `protobuf:"varint,5,opt,name=tuple_bytes_long,json=tupleBytesLong,proto3" json:"tuple_bytes_long,omitempty"`
	ChunksLong     uint64 `protobuf:"varint,6,opt,name=chunks_long,json=chunksLong,proto3" json:"chunks_long,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkStat) Reset() {
	*x = NetworkStat{}
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStat) ProtoMessage() {}

func (x *NetworkStat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStat.ProtoReflect.Descriptor instead.
func (*NetworkStat) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkStat) GetTotalBytes() uint32 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *NetworkStat) GetTupleBytes() uint32 {
	if x != nil {
		return x.TupleBytes
	}
	return 0
}

func (x *NetworkStat) GetChunks() uint32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

func (x *NetworkStat) GetTotalBytesLong() uint64 {
	if x != nil {
		return x.TotalBytesLong
	}
	return 0
}

func (x *NetworkStat) GetTupleBytesLong() uint64 {
	if x != nil {
		return x.TupleBytesLong
	}
	return 0
}

func (x *NetworkStat) GetChunksLong() uint64 {
	if x != nil {
		return x.ChunksLong
	}
	return 0
}

// InterconnectStat: detailed interconnect statistics.
type InterconnectStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total_recv_queue_size: max size of receive queue
	// of all backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: max
	TotalRecvQueueSize uint64 `protobuf:"varint,1,opt,name=total_recv_queue_size,json=totalRecvQueueSize,proto3" json:"total_recv_queue_size,omitempty"`
	// recv_queue_size_counting_time: total times when computation of total_recv_queue_size was performed
	// by all of backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: sum
	RecvQueueSizeCountingTime uint64 `protobuf:"varint,2,opt,name=recv_queue_size_counting_time,json=recvQueueSizeCountingTime,proto3" json:"recv_queue_size_counting_time,omitempty"`
	// total_capacity: max size of send queue
	// of all backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: max
	TotalCapacity uint64 `protobuf:"varint,3,opt,name=total_capacity,json=totalCapacity,proto3" json:"total_capacity,omitempty"`
	// capacity_counting_time: total times when computation of total_capacity was performed
	// by all of backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: sum
	CapacityCountingTime uint64 `protobuf:"varint,4,opt,name=capacity_counting_time,json=capacityCountingTime,proto3" json:"capacity_counting_time,omitempty"`
	// total_buffers: min buffers available before sent packets
	// of all backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: min
	TotalBuffers uint64 `protobuf:"varint,5,opt,name=total_buffers,json=totalBuffers,proto3" json:"total_buffers,omitempty"`
	// buffer_counting_time: total times when computation of total_buffers was performed
	// by all of backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: sum
	BufferCountingTime uint64 `protobuf:"varint,6,opt,name=buffer_counting_time,json=bufferCountingTime,proto3" json:"buffer_counting_time,omitempty"`
	// active_connections_num: max (among all of backends) outgoing connections number
	// made by all of backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: max
	ActiveConnectionsNum uint64 `protobuf:"varint,7,opt,name=active_connections_num,json=activeConnectionsNum,proto3" json:"active_connections_num,omitempty"`
	// retransmits: total number of retransmits
	// made by all of backend processes associated with query or session.
	//
	// Importance: major
	// Aggregation: sum
	Retransmits int64 `protobuf:"varint,8,opt,name=retransmits,proto3" json:"retransmits,omitempty"`
	// startup_cached_pkt_num: total number of cached future packets
	// cached by all of backend processes associated with query or session.
	// Counts only when gp_interconnect_cache_future_packets = on.
	//
	// Importance: minor
	// Aggregation: sum
	StartupCachedPktNum int64 `protobuf:"varint,9,opt,name=startup_cached_pkt_num,json=startupCachedPktNum,proto3" json:"startup_cached_pkt_num,omitempty"`
	// mismatch_num: total number of mismatched packets
	// received by all of backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: sum
	MismatchNum int64 `protobuf:"varint,10,opt,name=mismatch_num,json=mismatchNum,proto3" json:"mismatch_num,omitempty"`
	// crc_errors: total number of packets that failed CRC verification
	// verified by all of backend processes associated with query or session.
	// Counts only when gp_interconnect_full_crc = on.
	//
	// Importance: normal
	// Aggregation: sum
	CrcErrors int64 `protobuf:"varint,11,opt,name=crc_errors,json=crcErrors,proto3" json:"crc_errors,omitempty"`
	// snd_pkt_num: total number of outgoing packets
	// sent by all of backend processes associated with query or session.
	//
	// Importance: major
	// Aggregation: sum
	SndPktNum int64 `protobuf:"varint,12,opt,name=snd_pkt_num,json=sndPktNum,proto3" json:"snd_pkt_num,omitempty"`
	// recv_pkt_num: total number of incoming packets
	// received by all of backend processes associated with query or session.
	//
	// Importance: major
	// Aggregation: sum
	RecvPktNum int64 `protobuf:"varint,13,opt,name=recv_pkt_num,json=recvPktNum,proto3" json:"recv_pkt_num,omitempty"`
	// disordered_pkt_num: total number of disordered packets
	// received by all of backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: sum
	DisorderedPktNum int64 `protobuf:"varint,14,opt,name=disordered_pkt_num,json=disorderedPktNum,proto3" json:"disordered_pkt_num,omitempty"`
	// duplicated_pkt_num: total number of duplicated packets (already processed)
	// received by all of backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: sum
	DuplicatedPktNum int64 `protobuf:"varint,15,opt,name=duplicated_pkt_num,json=duplicatedPktNum,proto3" json:"duplicated_pkt_num,omitempty"`
	// recv_ack_num: total number of acknowledged packets
	// by all of backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: sum
	RecvAckNum int64 `protobuf:"varint,16,opt,name=recv_ack_num,json=recvAckNum,proto3" json:"recv_ack_num,omitempty"`
	// status_query_msg_num: total number of status packets
	// sent by all of backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: sum
	StatusQueryMsgNum int64 `protobuf:"varint,17,opt,name=status_query_msg_num,json=statusQueryMsgNum,proto3" json:"status_query_msg_num,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InterconnectStat) Reset() {
	*x = InterconnectStat{}
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterconnectStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterconnectStat) ProtoMessage() {}

func (x *InterconnectStat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterconnectStat.ProtoReflect.Descriptor instead.
func (*InterconnectStat) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *InterconnectStat) GetTotalRecvQueueSize() uint64 {
	if x != nil {
		return x.TotalRecvQueueSize
	}
	return 0
}

func (x *InterconnectStat) GetRecvQueueSizeCountingTime() uint64 {
	if x != nil {
		return x.RecvQueueSizeCountingTime
	}
	return 0
}

func (x *InterconnectStat) GetTotalCapacity() uint64 {
	if x != nil {
		return x.TotalCapacity
	}
	return 0
}

func (x *InterconnectStat) GetCapacityCountingTime() uint64 {
	if x != nil {
		return x.CapacityCountingTime
	}
	return 0
}

func (x *InterconnectStat) GetTotalBuffers() uint64 {
	if x != nil {
		return x.TotalBuffers
	}
	return 0
}

func (x *InterconnectStat) GetBufferCountingTime() uint64 {
	if x != nil {
		return x.BufferCountingTime
	}
	return 0
}

func (x *InterconnectStat) GetActiveConnectionsNum() uint64 {
	if x != nil {
		return x.ActiveConnectionsNum
	}
	return 0
}

func (x *InterconnectStat) GetRetransmits() int64 {
	if x != nil {
		return x.Retransmits
	}
	return 0
}

func (x *InterconnectStat) GetStartupCachedPktNum() int64 {
	if x != nil {
		return x.StartupCachedPktNum
	}
	return 0
}

func (x *InterconnectStat) GetMismatchNum() int64 {
	if x != nil {
		return x.MismatchNum
	}
	return 0
}

func (x *InterconnectStat) GetCrcErrors() int64 {
	if x != nil {
		return x.CrcErrors
	}
	return 0
}

func (x *InterconnectStat) GetSndPktNum() int64 {
	if x != nil {
		return x.SndPktNum
	}
	return 0
}

func (x *InterconnectStat) GetRecvPktNum() int64 {
	if x != nil {
		return x.RecvPktNum
	}
	return 0
}

func (x *InterconnectStat) GetDisorderedPktNum() int64 {
	if x != nil {
		return x.DisorderedPktNum
	}
	return 0
}

func (x *InterconnectStat) GetDuplicatedPktNum() int64 {
	if x != nil {
		return x.DuplicatedPktNum
	}
	return 0
}

func (x *InterconnectStat) GetRecvAckNum() int64 {
	if x != nil {
		return x.RecvAckNum
	}
	return 0
}

func (x *InterconnectStat) GetStatusQueryMsgNum() int64 {
	if x != nil {
		return x.StatusQueryMsgNum
	}
	return 0
}

// MetricInstrumentation: various statistics related to query plan nodes.
type MetricInstrumentation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ntuples: total number of tuples produced by plan nodes
	// by all nodes of all backend processes associated with query or session.
	//
	// Importance: normal (useless as aggregated value)
	// Aggregation: sum
	Ntuples uint64 `protobuf:"varint,1,opt,name=ntuples,proto3" json:"ntuples,omitempty"`
	// nloops: total number of times when all plan nodes
	// of all backend processes associated with query or session was executed.
	//
	// Importance: minor (useless as aggregated value)
	// Aggregation: sum
	Nloops uint64 `protobuf:"varint,2,opt,name=nloops,proto3" json:"nloops,omitempty"`
	// tuplecount: total number of tuples emitted so far the current cycle
	// by all nodes of all backend processes associated with query or session.
	//
	// Importance: minor (useless as aggregated value)
	// Aggregation: sum
	Tuplecount uint64 `protobuf:"varint,3,opt,name=tuplecount,proto3" json:"tuplecount,omitempty"`
	// firsttuple: total amount of time spent to get first tuple
	// by all nodes of all backend processes associated with query or session.
	//
	// Importance: minor (useless as aggregated value)
	// Aggregation: sum
	Firsttuple float64 `protobuf:"fixed64,4,opt,name=firsttuple,proto3" json:"firsttuple,omitempty"`
	// startup: total amount of time spent on queries startup (optimiser's cost estimation)
	// by all backend processes associated with query or session.
	//
	// Importance: minor (useless as aggregated value)
	// Aggregation: sum
	Startup float64 `protobuf:"fixed64,5,opt,name=startup,proto3" json:"startup,omitempty"`
	// total: total amount of time spent on queries total execution time
	// by all backend processes associated with query or session.
	//
	// Importance: minor (useless as aggregated value)
	// Aggregation: sum
	Total float64 `protobuf:"fixed64,6,opt,name=total,proto3" json:"total,omitempty"`
	// shared_blks_hit: total number of shared blocks hit
	// by all backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: sum
	SharedBlksHit uint64 `protobuf:"varint,7,opt,name=shared_blks_hit,json=sharedBlksHit,proto3" json:"shared_blks_hit,omitempty"`
	// shared_blks_read: total number of shared blocks read
	// by all backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: sum
	SharedBlksRead uint64 `protobuf:"varint,8,opt,name=shared_blks_read,json=sharedBlksRead,proto3" json:"shared_blks_read,omitempty"`
	// shared_blks_dirtied: total number of shared blocks dirtied
	// by all backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: sum
	SharedBlksDirtied uint64 `protobuf:"varint,9,opt,name=shared_blks_dirtied,json=sharedBlksDirtied,proto3" json:"shared_blks_dirtied,omitempty"`
	// shared_blks_written: total number of shared blocks written
	// by all backend processes associated with query or session.
	//
	// Importance: minor
	// Aggregation: sum
	SharedBlksWritten uint64 `protobuf:"varint,10,opt,name=shared_blks_written,json=sharedBlksWritten,proto3" json:"shared_blks_written,omitempty"`
	// local_blks_hit: total number of local blocks hit
	// by all backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: sum
	LocalBlksHit uint64 `protobuf:"varint,11,opt,name=local_blks_hit,json=localBlksHit,proto3" json:"local_blks_hit,omitempty"`
	// local_blks_read: total number of local blocks read
	// by all backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: sum
	LocalBlksRead uint64 `protobuf:"varint,12,opt,name=local_blks_read,json=localBlksRead,proto3" json:"local_blks_read,omitempty"`
	// local_blks_dirtied: total number of local blocks dirtied
	// by all backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: sum
	LocalBlksDirtied uint64 `protobuf:"varint,13,opt,name=local_blks_dirtied,json=localBlksDirtied,proto3" json:"local_blks_dirtied,omitempty"`
	// local_blks_written: total number of local blocks written
	// by all backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: sum
	LocalBlksWritten uint64 `protobuf:"varint,14,opt,name=local_blks_written,json=localBlksWritten,proto3" json:"local_blks_written,omitempty"`
	// temp_blks_read: total number of temp blocks read
	// by all backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: sum
	TempBlksRead uint64 `protobuf:"varint,15,opt,name=temp_blks_read,json=tempBlksRead,proto3" json:"temp_blks_read,omitempty"` // temporary tables read stat
	// temp_blks_written: total number of temp blocks written
	// by all backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: sum
	TempBlksWritten uint64 `protobuf:"varint,16,opt,name=temp_blks_written,json=tempBlksWritten,proto3" json:"temp_blks_written,omitempty"`
	// blk_read_time: total amount of time spent reading data blocks
	// by all backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: sum
	BlkReadTime float64 `protobuf:"fixed64,17,opt,name=blk_read_time,json=blkReadTime,proto3" json:"blk_read_time,omitempty"`
	// blk_write_time: total amount of time spent writing data blocks
	// by all backend processes associated with query or session.
	//
	// Importance: normal
	// Aggregation: sum
	BlkWriteTime float64 `protobuf:"fixed64,18,opt,name=blk_write_time,json=blkWriteTime,proto3" json:"blk_write_time,omitempty"`
	// sent: basic network statistics for all of backend processes
	// associated with query or session sent to the network layer.
	Sent *NetworkStat `protobuf:"bytes,19,opt,name=sent,proto3" json:"sent,omitempty"`
	// received: basic network statistics for all of backend processes
	// associated with query or session received from the network layer.
	Received *NetworkStat `protobuf:"bytes,20,opt,name=received,proto3" json:"received,omitempty"`
	// startup_time: total amount of time spent on queries startup (planning + queue time)
	// by all backend processes associated with query or session.
	//
	// Importance: minor (useless as aggregated value, also possible duplicate of startup)
	// Aggregation: sum
	StartupTime float64 `protobuf:"fixed64,21,opt,name=startup_time,json=startupTime,proto3" json:"startup_time,omitempty"`
	// inherited_calls: total number of executed nested queries (sub-queries)
	// by all backend processes associated with query or session.
	//
	// Importance: major
	// Aggregation: sum
	InheritedCalls uint64 `protobuf:"varint,22,opt,name=inherited_calls,json=inheritedCalls,proto3" json:"inherited_calls,omitempty"`
	// inherited_time: total amount of time (in seconds) spent on executing nested queries (sub-queries)
	// by all backend processes associated with the query or session.
	//
	// Importance: major
	// Aggregation: sum
	InheritedTime float64 `protobuf:"fixed64,23,opt,name=inherited_time,json=inheritedTime,proto3" json:"inherited_time,omitempty"`
	// interconnect: detailed interconnect statistics.
	Interconnect  *InterconnectStat `protobuf:"bytes,24,opt,name=interconnect,proto3" json:"interconnect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricInstrumentation) Reset() {
	*x = MetricInstrumentation{}
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricInstrumentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricInstrumentation) ProtoMessage() {}

func (x *MetricInstrumentation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricInstrumentation.ProtoReflect.Descriptor instead.
func (*MetricInstrumentation) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *MetricInstrumentation) GetNtuples() uint64 {
	if x != nil {
		return x.Ntuples
	}
	return 0
}

func (x *MetricInstrumentation) GetNloops() uint64 {
	if x != nil {
		return x.Nloops
	}
	return 0
}

func (x *MetricInstrumentation) GetTuplecount() uint64 {
	if x != nil {
		return x.Tuplecount
	}
	return 0
}

func (x *MetricInstrumentation) GetFirsttuple() float64 {
	if x != nil {
		return x.Firsttuple
	}
	return 0
}

func (x *MetricInstrumentation) GetStartup() float64 {
	if x != nil {
		return x.Startup
	}
	return 0
}

func (x *MetricInstrumentation) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MetricInstrumentation) GetSharedBlksHit() uint64 {
	if x != nil {
		return x.SharedBlksHit
	}
	return 0
}

func (x *MetricInstrumentation) GetSharedBlksRead() uint64 {
	if x != nil {
		return x.SharedBlksRead
	}
	return 0
}

func (x *MetricInstrumentation) GetSharedBlksDirtied() uint64 {
	if x != nil {
		return x.SharedBlksDirtied
	}
	return 0
}

func (x *MetricInstrumentation) GetSharedBlksWritten() uint64 {
	if x != nil {
		return x.SharedBlksWritten
	}
	return 0
}

func (x *MetricInstrumentation) GetLocalBlksHit() uint64 {
	if x != nil {
		return x.LocalBlksHit
	}
	return 0
}

func (x *MetricInstrumentation) GetLocalBlksRead() uint64 {
	if x != nil {
		return x.LocalBlksRead
	}
	return 0
}

func (x *MetricInstrumentation) GetLocalBlksDirtied() uint64 {
	if x != nil {
		return x.LocalBlksDirtied
	}
	return 0
}

func (x *MetricInstrumentation) GetLocalBlksWritten() uint64 {
	if x != nil {
		return x.LocalBlksWritten
	}
	return 0
}

func (x *MetricInstrumentation) GetTempBlksRead() uint64 {
	if x != nil {
		return x.TempBlksRead
	}
	return 0
}

func (x *MetricInstrumentation) GetTempBlksWritten() uint64 {
	if x != nil {
		return x.TempBlksWritten
	}
	return 0
}

func (x *MetricInstrumentation) GetBlkReadTime() float64 {
	if x != nil {
		return x.BlkReadTime
	}
	return 0
}

func (x *MetricInstrumentation) GetBlkWriteTime() float64 {
	if x != nil {
		return x.BlkWriteTime
	}
	return 0
}

func (x *MetricInstrumentation) GetSent() *NetworkStat {
	if x != nil {
		return x.Sent
	}
	return nil
}

func (x *MetricInstrumentation) GetReceived() *NetworkStat {
	if x != nil {
		return x.Received
	}
	return nil
}

func (x *MetricInstrumentation) GetStartupTime() float64 {
	if x != nil {
		return x.StartupTime
	}
	return 0
}

func (x *MetricInstrumentation) GetInheritedCalls() uint64 {
	if x != nil {
		return x.InheritedCalls
	}
	return 0
}

func (x *MetricInstrumentation) GetInheritedTime() float64 {
	if x != nil {
		return x.InheritedTime
	}
	return 0
}

func (x *MetricInstrumentation) GetInterconnect() *InterconnectStat {
	if x != nil {
		return x.Interconnect
	}
	return nil
}

// SpillInfo: detailed statistics about produced spill files.
type SpillInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fileCount: total number of spill files
	// created by all of backend processes associated with query or session.
	//
	// Importance: major
	// Aggregation: sum
	FileCount int32 `protobuf:"varint,1,opt,name=fileCount,proto3" json:"fileCount,omitempty"`
	// totalBytes: total size of produced spill files
	// created by all of backend processes associated with query or session.
	//
	// Importance: major
	// Aggregation: sum
	TotalBytes    int64 `protobuf:"varint,2,opt,name=totalBytes,proto3" json:"totalBytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpillInfo) Reset() {
	*x = SpillInfo{}
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpillInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpillInfo) ProtoMessage() {}

func (x *SpillInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpillInfo.ProtoReflect.Descriptor instead.
func (*SpillInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *SpillInfo) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *SpillInfo) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

var File_api_proto_common_yagpcc_metrics_proto protoreflect.FileDescriptor

const file_api_proto_common_yagpcc_metrics_proto_rawDesc = "" +
	"\n" +
	"%api/proto/common/yagpcc_metrics.proto\x12\x06yagpcc\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x04\n" +
	"\tQueryInfo\x123\n" +
	"\tgenerator\x18\x01 \x01(\x0e2\x15.yagpcc.PlanGeneratorR\tgenerator\x12\x19\n" +
	"\bquery_id\x18\x02 \x01(\x04R\aqueryId\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\x04R\x06planId\x12\x1d\n" +
	"\n" +
	"query_text\x18\x04 \x01(\tR\tqueryText\x12\x1b\n" +
	"\tplan_text\x18\x05 \x01(\tR\bplanText\x122\n" +
	"\x13template_query_text\x18\x06 \x01(\tB\x02\x18\x01R\x11templateQueryText\x120\n" +
	"\x12template_plan_text\x18\a \x01(\tB\x02\x18\x01R\x10templatePlanText\x12\x1a\n" +
	"\buserName\x18\b \x01(\tR\buserName\x12\"\n" +
	"\fdatabaseName\x18\t \x01(\tR\fdatabaseName\x12\x18\n" +
	"\arsgname\x18\n" +
	" \x01(\tR\arsgname\x12!\n" +
	"\fanalyze_text\x18\v \x01(\tR\vanalyzeText\x12;\n" +
	"\vsubmit_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"submitTime\x129\n" +
	"\n" +
	"start_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"x\n" +
	"\x13AdditionalQueryInfo\x12!\n" +
	"\fnested_level\x18\x01 \x01(\x03R\vnestedLevel\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bslice_id\x18\x03 \x01(\x03R\asliceId\":\n" +
	"\x13AdditionalQueryStat\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\"\xb1\x01\n" +
	"\tGPMetrics\x122\n" +
	"\n" +
	"systemStat\x18\x01 \x01(\v2\x12.yagpcc.SystemStatR\n" +
	"systemStat\x12G\n" +
	"\x0finstrumentation\x18\x02 \x01(\v2\x1d.yagpcc.MetricInstrumentationR\x0finstrumentation\x12'\n" +
	"\x05spill\x18\x03 \x01(\v2\x11.yagpcc.SpillInfoR\x05spill\"F\n" +
	"\bQueryKey\x12\x12\n" +
	"\x04tmid\x18\x01 \x01(\x05R\x04tmid\x12\x12\n" +
	"\x04ssid\x18\x02 \x01(\x05R\x04ssid\x12\x12\n" +
	"\x04ccnt\x18\x03 \x01(\x05R\x04ccnt\"<\n" +
	"\n" +
	"SegmentKey\x12\x12\n" +
	"\x04dbid\x18\x01 \x01(\x05R\x04dbid\x12\x1a\n" +
	"\bsegindex\x18\x02 \x01(\x05R\bsegindex\"\xc4\x03\n" +
	"\n" +
	"SystemStat\x12.\n" +
	"\x12runningTimeSeconds\x18\x01 \x01(\x01R\x12runningTimeSeconds\x12(\n" +
	"\x0fuserTimeSeconds\x18\x02 \x01(\x01R\x0fuserTimeSeconds\x12,\n" +
	"\x11kernelTimeSeconds\x18\x03 \x01(\x01R\x11kernelTimeSeconds\x12\x14\n" +
	"\x05vsize\x18\x04 \x01(\x04R\x05vsize\x12\x10\n" +
	"\x03rss\x18\x05 \x01(\x04R\x03rss\x12\x1e\n" +
	"\bVmSizeKb\x18\x06 \x01(\x04B\x02\x18\x01R\bVmSizeKb\x12\x1a\n" +
	"\bVmPeakKb\x18\a \x01(\x04R\bVmPeakKb\x12\x14\n" +
	"\x05rchar\x18\b \x01(\x04R\x05rchar\x12\x14\n" +
	"\x05wchar\x18\t \x01(\x04R\x05wchar\x12\x14\n" +
	"\x05syscr\x18\n" +
	" \x01(\x04R\x05syscr\x12\x14\n" +
	"\x05syscw\x18\v \x01(\x04R\x05syscw\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\f \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\r \x01(\x04R\n" +
	"writeBytes\x122\n" +
	"\x15cancelled_write_bytes\x18\x0e \x01(\x04R\x13cancelledWriteBytes\"\xdc\x01\n" +
	"\vNetworkStat\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\rR\n" +
	"totalBytes\x12\x1f\n" +
	"\vtuple_bytes\x18\x02 \x01(\rR\n" +
	"tupleBytes\x12\x16\n" +
	"\x06chunks\x18\x03 \x01(\rR\x06chunks\x12(\n" +
	"\x10total_bytes_long\x18\x04 \x01(\x04R\x0etotalBytesLong\x12(\n" +
	"\x10tuple_bytes_long\x18\x05 \x01(\x04R\x0etupleBytesLong\x12\x1f\n" +
	"\vchunks_long\x18\x06 \x01(\x04R\n" +
	"chunksLong\"\xfb\x05\n" +
	"\x10InterconnectStat\x121\n" +
	"\x15total_recv_queue_size\x18\x01 \x01(\x04R\x12totalRecvQueueSize\x12@\n" +
	"\x1drecv_queue_size_counting_time\x18\x02 \x01(\x04R\x19recvQueueSizeCountingTime\x12%\n" +
	"\x0etotal_capacity\x18\x03 \x01(\x04R\rtotalCapacity\x124\n" +
	"\x16capacity_counting_time\x18\x04 \x01(\x04R\x14capacityCountingTime\x12#\n" +
	"\rtotal_buffers\x18\x05 \x01(\x04R\ftotalBuffers\x120\n" +
	"\x14buffer_counting_time\x18\x06 \x01(\x04R\x12bufferCountingTime\x124\n" +
	"\x16active_connections_num\x18\a \x01(\x04R\x14activeConnectionsNum\x12 \n" +
	"\vretransmits\x18\b \x01(\x03R\vretransmits\x123\n" +
	"\x16startup_cached_pkt_num\x18\t \x01(\x03R\x13startupCachedPktNum\x12!\n" +
	"\fmismatch_num\x18\n" +
	" \x01(\x03R\vmismatchNum\x12\x1d\n" +
	"\n" +
	"crc_errors\x18\v \x01(\x03R\tcrcErrors\x12\x1e\n" +
	"\vsnd_pkt_num\x18\f \x01(\x03R\tsndPktNum\x12 \n" +
	"\frecv_pkt_num\x18\r \x01(\x03R\n" +
	"recvPktNum\x12,\n" +
	"\x12disordered_pkt_num\x18\x0e \x01(\x03R\x10disorderedPktNum\x12,\n" +
	"\x12duplicated_pkt_num\x18\x0f \x01(\x03R\x10duplicatedPktNum\x12 \n" +
	"\frecv_ack_num\x18\x10 \x01(\x03R\n" +
	"recvAckNum\x12/\n" +
	"\x14status_query_msg_num\x18\x11 \x01(\x03R\x11statusQueryMsgNum\"\xbc\a\n" +
	"\x15MetricInstrumentation\x12\x18\n" +
	"\antuples\x18\x01 \x01(\x04R\antuples\x12\x16\n" +
	"\x06nloops\x18\x02 \x01(\x04R\x06nloops\x12\x1e\n" +
	"\n" +
	"tuplecount\x18\x03 \x01(\x04R\n" +
	"tuplecount\x12\x1e\n" +
	"\n" +
	"firsttuple\x18\x04 \x01(\x01R\n" +
	"firsttuple\x12\x18\n" +
	"\astartup\x18\x05 \x01(\x01R\astartup\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x01R\x05total\x12&\n" +
	"\x0fshared_blks_hit\x18\a \x01(\x04R\rsharedBlksHit\x12(\n" +
	"\x10shared_blks_read\x18\b \x01(\x04R\x0esharedBlksRead\x12.\n" +
	"\x13shared_blks_dirtied\x18\t \x01(\x04R\x11sharedBlksDirtied\x12.\n" +
	"\x13shared_blks_written\x18\n" +
	" \x01(\x04R\x11sharedBlksWritten\x12$\n" +
	"\x0elocal_blks_hit\x18\v \x01(\x04R\flocalBlksHit\x12&\n" +
	"\x0flocal_blks_read\x18\f \x01(\x04R\rlocalBlksRead\x12,\n" +
	"\x12local_blks_dirtied\x18\r \x01(\x04R\x10localBlksDirtied\x12,\n" +
	"\x12local_blks_written\x18\x0e \x01(\x04R\x10localBlksWritten\x12$\n" +
	"\x0etemp_blks_read\x18\x0f \x01(\x04R\ftempBlksRead\x12*\n" +
	"\x11temp_blks_written\x18\x10 \x01(\x04R\x0ftempBlksWritten\x12\"\n" +
	"\rblk_read_time\x18\x11 \x01(\x01R\vblkReadTime\x12$\n" +
	"\x0eblk_write_time\x18\x12 \x01(\x01R\fblkWriteTime\x12'\n" +
	"\x04sent\x18\x13 \x01(\v2\x13.yagpcc.NetworkStatR\x04sent\x12/\n" +
	"\breceived\x18\x14 \x01(\v2\x13.yagpcc.NetworkStatR\breceived\x12!\n" +
	"\fstartup_time\x18\x15 \x01(\x01R\vstartupTime\x12'\n" +
	"\x0finherited_calls\x18\x16 \x01(\x04R\x0einheritedCalls\x12%\n" +
	"\x0einherited_time\x18\x17 \x01(\x01R\rinheritedTime\x12<\n" +
	"\finterconnect\x18\x18 \x01(\v2\x18.yagpcc.InterconnectStatR\finterconnect\"I\n" +
	"\tSpillInfo\x12\x1c\n" +
	"\tfileCount\x18\x01 \x01(\x05R\tfileCount\x12\x1e\n" +
	"\n" +
	"totalBytes\x18\x02 \x01(\x03R\n" +
	"totalBytes*\xf6\x01\n" +
	"\vQueryStatus\x12\x1c\n" +
	"\x18QUERY_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13QUERY_STATUS_SUBMIT\x10\x01\x12\x16\n" +
	"\x12QUERY_STATUS_START\x10\x02\x12\x15\n" +
	"\x11QUERY_STATUS_DONE\x10\x03\x12\x1b\n" +
	"\x17QUERY_STATUS_QUERY_DONE\x10\x04\x12\x16\n" +
	"\x12QUERY_STATUS_ERROR\x10\x05\x12\x1b\n" +
	"\x17QUERY_STATUS_CANCELLING\x10\x06\x12\x19\n" +
	"\x15QUERY_STATUS_CANCELED\x10\a\x12\x14\n" +
	"\x10QUERY_STATUS_END\x10\b*i\n" +
	"\rPlanGenerator\x12\x1e\n" +
	"\x1aPLAN_GENERATOR_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PLAN_GENERATOR_PLANNER\x10\x01\x12\x1c\n" +
	"\x18PLAN_GENERATOR_OPTIMIZER\x10\x02BHB\x0eSegmentYAGPCCMZ6github.com/open-gpdb/yagpcc/api/proto/common;greenplumb\x06proto3"

var (
	file_api_proto_common_yagpcc_metrics_proto_rawDescOnce sync.Once
	file_api_proto_common_yagpcc_metrics_proto_rawDescData []byte
)

func file_api_proto_common_yagpcc_metrics_proto_rawDescGZIP() []byte {
	file_api_proto_common_yagpcc_metrics_proto_rawDescOnce.Do(func() {
		file_api_proto_common_yagpcc_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_common_yagpcc_metrics_proto_rawDesc), len(file_api_proto_common_yagpcc_metrics_proto_rawDesc)))
	})
	return file_api_proto_common_yagpcc_metrics_proto_rawDescData
}

var file_api_proto_common_yagpcc_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_common_yagpcc_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_common_yagpcc_metrics_proto_goTypes = []any{
	(QueryStatus)(0),              // 0: yagpcc.QueryStatus
	(PlanGenerator)(0),            // 1: yagpcc.PlanGenerator
	(*QueryInfo)(nil),             // 2: yagpcc.QueryInfo
	(*AdditionalQueryInfo)(nil),   // 3: yagpcc.AdditionalQueryInfo
	(*AdditionalQueryStat)(nil),   // 4: yagpcc.AdditionalQueryStat
	(*GPMetrics)(nil),             // 5: yagpcc.GPMetrics
	(*QueryKey)(nil),              // 6: yagpcc.QueryKey
	(*SegmentKey)(nil),            // 7: yagpcc.SegmentKey
	(*SystemStat)(nil),            // 8: yagpcc.SystemStat
	(*NetworkStat)(nil),           // 9: yagpcc.NetworkStat
	(*InterconnectStat)(nil),      // 10: yagpcc.InterconnectStat
	(*MetricInstrumentation)(nil), // 11: yagpcc.MetricInstrumentation
	(*SpillInfo)(nil),             // 12: yagpcc.SpillInfo
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_api_proto_common_yagpcc_metrics_proto_depIdxs = []int32{
	1,  // 0: yagpcc.QueryInfo.generator:type_name -> yagpcc.PlanGenerator
	13, // 1: yagpcc.QueryInfo.submit_time:type_name -> google.protobuf.Timestamp
	13, // 2: yagpcc.QueryInfo.start_time:type_name -> google.protobuf.Timestamp
	13, // 3: yagpcc.QueryInfo.end_time:type_name -> google.protobuf.Timestamp
	8,  // 4: yagpcc.GPMetrics.systemStat:type_name -> yagpcc.SystemStat
	11, // 5: yagpcc.GPMetrics.instrumentation:type_name -> yagpcc.MetricInstrumentation
	12, // 6: yagpcc.GPMetrics.spill:type_name -> yagpcc.SpillInfo
	9,  // 7: yagpcc.MetricInstrumentation.sent:type_name -> yagpcc.NetworkStat
	9,  // 8: yagpcc.MetricInstrumentation.received:type_name -> yagpcc.NetworkStat
	10, // 9: yagpcc.MetricInstrumentation.interconnect:type_name -> yagpcc.InterconnectStat
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_common_yagpcc_metrics_proto_init() }
func file_api_proto_common_yagpcc_metrics_proto_init() {
	if File_api_proto_common_yagpcc_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_common_yagpcc_metrics_proto_rawDesc), len(file_api_proto_common_yagpcc_metrics_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_common_yagpcc_metrics_proto_goTypes,
		DependencyIndexes: file_api_proto_common_yagpcc_metrics_proto_depIdxs,
		EnumInfos:         file_api_proto_common_yagpcc_metrics_proto_enumTypes,
		MessageInfos:      file_api_proto_common_yagpcc_metrics_proto_msgTypes,
	}.Build()
	File_api_proto_common_yagpcc_metrics_proto = out.File
	file_api_proto_common_yagpcc_metrics_proto_goTypes = nil
	file_api_proto_common_yagpcc_metrics_proto_depIdxs = nil
}
