// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/common/yagpcc_session.proto

package greenplum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionKey: represents compound cluster wide unique session identifier.
type SessionKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sess_id: session identifier from pg_stat_activity system view.
	SessId int64 `protobuf:"varint,1,opt,name=sess_id,json=sessId,proto3" json:"sess_id,omitempty"`
	// tm_id: made up identifier to ensure SessionKey uniqueness through all cluster lifetime.
	// It is calculated based on the epoch time of the postmaster start time as following:
	//
	//	cast(extract(epoch from pg_postmaster_start_time())
	TmId          int64 `protobuf:"varint,2,opt,name=tm_id,json=tmId,proto3" json:"tm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionKey) Reset() {
	*x = SessionKey{}
	mi := &file_api_proto_common_yagpcc_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionKey) ProtoMessage() {}

func (x *SessionKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionKey.ProtoReflect.Descriptor instead.
func (*SessionKey) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_session_proto_rawDescGZIP(), []int{0}
}

func (x *SessionKey) GetSessId() int64 {
	if x != nil {
		return x.SessId
	}
	return 0
}

func (x *SessionKey) GetTmId() int64 {
	if x != nil {
		return x.TmId
	}
	return 0
}

// SessionInfo: various session statistics collected mostly from pg_stat_activity on primary master.
type SessionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pid: process ID for the session backend on primary master.
	// Same as pg_stat_activity.pid.
	Pid int64 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// database: name of the database used by session.
	// Same as pg_stat_activity.datname.
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// user: name of the user logged into this backend.
	// Same as pg_stat_activity.usename.
	User string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// application_name: name of the application that is connected to this backend.
	// Same as pg_stat_activity.application_name.
	ApplicationName string `protobuf:"bytes,4,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// client_addr: IP address of the client connected to this backend.
	// If this field is null, it indicates either that the client is connected via a Unix socket on the server machine
	// or that this is an internal process such as autovacuum.
	// A value of 'localhost' or '127.0.0.1' indicates that the connection is local or goes through a connection pooler.
	// Same as pg_stat_activity.client_addr.
	ClientAddr string `protobuf:"bytes,5,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"`
	// client_hostname: host name of the connected client, as reported by a reverse DNS lookup of client_addr.
	// This field will only be non-null for IP connections, and only when log_hostname is enabled.
	// Same as pg_stat_activity.client_hostname.
	ClientHostname string `protobuf:"bytes,6,opt,name=client_hostname,json=clientHostname,proto3" json:"client_hostname,omitempty"`
	// client_port: TCP port number that the client is using for communication with this backend,
	// or -1 if a Unix socket is used
	// Same as pg_stat_activity.client_port.
	ClientPort int64 `protobuf:"varint,7,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	// backend_start: time backend process was started.
	// Same as pg_stat_activity.backend_start.
	BackendStart *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=backend_start,json=backendStart,proto3" json:"backend_start,omitempty"`
	// xact_start: transaction start time.
	// If this field is null, it indicates that there is no transaction in progress in the session.
	// Same as pg_stat_activity.xact_start.
	XactStart *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=xact_start,json=xactStart,proto3" json:"xact_start,omitempty"`
	// query_start: time query began execution.
	// If this field is null, it indicates that no query was executed in the session.
	// Same as pg_stat_activity.query_start.
	QueryStart *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=query_start,json=queryStart,proto3" json:"query_start,omitempty"`
	// state_change: time when the `state` was last changed.
	// Same as pg_stat_activity.state_change.
	StateChange *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=state_change,json=stateChange,proto3" json:"state_change,omitempty"`
	// waiting_reason: reason the session is waiting.
	// The value can be: lock, replication, or resgroup.
	// Same as pg_stat_activity.waiting_reason.
	WaitingReason string `protobuf:"bytes,12,opt,name=waiting_reason,json=waitingReason,proto3" json:"waiting_reason,omitempty"`
	// waiting: true if waiting on a lock, false if not waiting.
	// Same as pg_stat_activity.waiting.
	Waiting bool `protobuf:"varint,13,opt,name=waiting,proto3" json:"waiting,omitempty"`
	// state: current overall state of the session.
	// Same as pg_stat_activity.state.
	State string `protobuf:"bytes,14,opt,name=state,proto3" json:"state,omitempty"`
	// backend_xid: top-level transaction identifier of this session, if any.
	// Same as pg_stat_activity.backend_xid.
	BackendXid string `protobuf:"bytes,15,opt,name=backend_xid,json=backendXid,proto3" json:"backend_xid,omitempty"`
	// backend_xmin: the session's xmin horizon.
	// Same as pg_stat_activity.backend_xmin.
	BackendXmin string `protobuf:"bytes,16,opt,name=backend_xmin,json=backendXmin,proto3" json:"backend_xmin,omitempty"`
	// rsgid: resource group OID or `0`.
	// Same as pg_stat_activity.rsgid and pg_resgroup.oid.
	Rsgid int64 `protobuf:"varint,17,opt,name=rsgid,proto3" json:"rsgid,omitempty"`
	// rsgname: resource group name or `unknown`.
	// Same as pg_stat_activity.rsgname and pg_resgroup.rsgname.
	Rsgname string `protobuf:"bytes,18,opt,name=rsgname,proto3" json:"rsgname,omitempty"`
	// rsgqueueduration: for a queued query, the total time the query has been queued.
	// Same as pg_stat_activity.rsgqueueduration.
	Rsgqueueduration string `protobuf:"bytes,19,opt,name=rsgqueueduration,proto3" json:"rsgqueueduration,omitempty"`
	// blocked_by_sess_id: identifier of a session that blocks the current session.
	// Same as pg_stat_activity.sess_id and pg_locks.mppsessionid.
	BlockedBySessId int64 `protobuf:"varint,20,opt,name=blocked_by_sess_id,json=blockedBySessId,proto3" json:"blocked_by_sess_id,omitempty"`
	// wait_mode: name of the lock mode desired by the current session.
	// Same as pg_lock.mode.
	WaitMode string `protobuf:"bytes,21,opt,name=wait_mode,json=waitMode,proto3" json:"wait_mode,omitempty"`
	// locked_item: name of the relation targeted by the lock or type of the lockable object.
	// Calculated as following:
	//
	//	coalesce(cast(cast(pg_lock.relation AS regclass) AS text), pg_lock.locktype).
	LockedItem string `protobuf:"bytes,22,opt,name=locked_item,json=lockedItem,proto3" json:"locked_item,omitempty"`
	// locked_mode: name of the lock mode held by `blocked_by_sess_id` session.
	// Same as pg_lock.mode.
	LockedMode    string `protobuf:"bytes,23,opt,name=locked_mode,json=lockedMode,proto3" json:"locked_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_api_proto_common_yagpcc_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_session_proto_rawDescGZIP(), []int{1}
}

func (x *SessionInfo) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SessionInfo) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *SessionInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SessionInfo) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *SessionInfo) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

func (x *SessionInfo) GetClientHostname() string {
	if x != nil {
		return x.ClientHostname
	}
	return ""
}

func (x *SessionInfo) GetClientPort() int64 {
	if x != nil {
		return x.ClientPort
	}
	return 0
}

func (x *SessionInfo) GetBackendStart() *timestamppb.Timestamp {
	if x != nil {
		return x.BackendStart
	}
	return nil
}

func (x *SessionInfo) GetXactStart() *timestamppb.Timestamp {
	if x != nil {
		return x.XactStart
	}
	return nil
}

func (x *SessionInfo) GetQueryStart() *timestamppb.Timestamp {
	if x != nil {
		return x.QueryStart
	}
	return nil
}

func (x *SessionInfo) GetStateChange() *timestamppb.Timestamp {
	if x != nil {
		return x.StateChange
	}
	return nil
}

func (x *SessionInfo) GetWaitingReason() string {
	if x != nil {
		return x.WaitingReason
	}
	return ""
}

func (x *SessionInfo) GetWaiting() bool {
	if x != nil {
		return x.Waiting
	}
	return false
}

func (x *SessionInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SessionInfo) GetBackendXid() string {
	if x != nil {
		return x.BackendXid
	}
	return ""
}

func (x *SessionInfo) GetBackendXmin() string {
	if x != nil {
		return x.BackendXmin
	}
	return ""
}

func (x *SessionInfo) GetRsgid() int64 {
	if x != nil {
		return x.Rsgid
	}
	return 0
}

func (x *SessionInfo) GetRsgname() string {
	if x != nil {
		return x.Rsgname
	}
	return ""
}

func (x *SessionInfo) GetRsgqueueduration() string {
	if x != nil {
		return x.Rsgqueueduration
	}
	return ""
}

func (x *SessionInfo) GetBlockedBySessId() int64 {
	if x != nil {
		return x.BlockedBySessId
	}
	return 0
}

func (x *SessionInfo) GetWaitMode() string {
	if x != nil {
		return x.WaitMode
	}
	return ""
}

func (x *SessionInfo) GetLockedItem() string {
	if x != nil {
		return x.LockedItem
	}
	return ""
}

func (x *SessionInfo) GetLockedMode() string {
	if x != nil {
		return x.LockedMode
	}
	return ""
}

// QueryDesc: contains detailed information about a query,
// including its unique identifier, status, and execution details.
type QueryDesc struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query_key: compound cluster wide unique query identifier.
	QueryKey *QueryKey `protobuf:"bytes,1,opt,name=query_key,json=queryKey,proto3" json:"query_key,omitempty"`
	// query_info: various attributes of the query.
	QueryInfo *QueryInfo `protobuf:"bytes,2,opt,name=query_info,json=queryInfo,proto3" json:"query_info,omitempty"`
	// query_status: the query status.
	QueryStatus QueryStatus `protobuf:"varint,3,opt,name=query_status,json=queryStatus,proto3,enum=yagpcc.QueryStatus" json:"query_status,omitempty"`
	// query_level: level of the query nesting.
	QueryLevel int64 `protobuf:"varint,4,opt,name=query_level,json=queryLevel,proto3" json:"query_level,omitempty"`
	// query_start: query start timestamp.
	QueryStart    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=query_start,json=queryStart,proto3" json:"query_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDesc) Reset() {
	*x = QueryDesc{}
	mi := &file_api_proto_common_yagpcc_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDesc) ProtoMessage() {}

func (x *QueryDesc) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDesc.ProtoReflect.Descriptor instead.
func (*QueryDesc) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_session_proto_rawDescGZIP(), []int{2}
}

func (x *QueryDesc) GetQueryKey() *QueryKey {
	if x != nil {
		return x.QueryKey
	}
	return nil
}

func (x *QueryDesc) GetQueryInfo() *QueryInfo {
	if x != nil {
		return x.QueryInfo
	}
	return nil
}

func (x *QueryDesc) GetQueryStatus() QueryStatus {
	if x != nil {
		return x.QueryStatus
	}
	return QueryStatus_QUERY_STATUS_UNSPECIFIED
}

func (x *QueryDesc) GetQueryLevel() int64 {
	if x != nil {
		return x.QueryLevel
	}
	return 0
}

func (x *QueryDesc) GetQueryStart() *timestamppb.Timestamp {
	if x != nil {
		return x.QueryStart
	}
	return nil
}

// SessionState: represents various session related statistics.
type SessionState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// time: timestamp when statistics was collected.
	Time *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	// cluster_id: unique identifier of the cluster.
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// hostname: host name of the master primary host.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// session_key: cluster wide unique session identifier.
	SessionKey *SessionKey `protobuf:"bytes,4,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	// session_info: various session statistics collected mostly from pg_stat_activity on primary master.
	SessionInfo *SessionInfo `protobuf:"bytes,5,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	// running_query: cluster wide unique query identifier of the currently executing query.
	RunningQuery *QueryKey `protobuf:"bytes,6,opt,name=running_query,json=runningQuery,proto3" json:"running_query,omitempty"`
	// running_query_info: various attributes of the currently executing query.
	RunningQueryInfo *QueryInfo `protobuf:"bytes,7,opt,name=running_query_info,json=runningQueryInfo,proto3" json:"running_query_info,omitempty"`
	// running_query_status: status of the currently executing query.
	RunningQueryStatus QueryStatus `protobuf:"varint,8,opt,name=running_query_status,json=runningQueryStatus,proto3,enum=yagpcc.QueryStatus" json:"running_query_status,omitempty"`
	// total_metrics: various aggregated statistics for the whole session.
	TotalMetrics *GPMetrics `protobuf:"bytes,9,opt,name=total_metrics,json=totalMetrics,proto3" json:"total_metrics,omitempty"`
	// last_metrics: various aggregated statistics for the whole session within 1h time window (now() - 1h).
	LastMetrics *GPMetrics `protobuf:"bytes,10,opt,name=last_metrics,json=lastMetrics,proto3" json:"last_metrics,omitempty"`
	// query_metrics: various aggregated statistics for the currently executing query.
	QueryMetrics *GPMetrics `protobuf:"bytes,11,opt,name=query_metrics,json=queryMetrics,proto3" json:"query_metrics,omitempty"`
	// running_query_level: nesting level for the currently executing query.
	RunningQueryLevel int64 `protobuf:"varint,12,opt,name=running_query_level,json=runningQueryLevel,proto3" json:"running_query_level,omitempty"`
	// running_queries_stack: a stack of nested queries related to the currently executing query.
	RunningQueriesStack []*QueryDesc `protobuf:"bytes,13,rep,name=running_queries_stack,json=runningQueriesStack,proto3" json:"running_queries_stack,omitempty"`
	// blocked_session_level: level of blocked session if session is blocked.
	BlockedSessionLevel int64 `protobuf:"varint,14,opt,name=blocked_session_level,json=blockedSessionLevel,proto3" json:"blocked_session_level,omitempty"`
	// running_query_error: error message for the currently executing query.
	RunningQueryError string `protobuf:"bytes,15,opt,name=running_query_error,json=runningQueryError,proto3" json:"running_query_error,omitempty"`
	// running_query_slices: total number of slices used for the currently executing query.
	RunningQuerySlices int64 `protobuf:"varint,16,opt,name=running_query_slices,json=runningQuerySlices,proto3" json:"running_query_slices,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SessionState) Reset() {
	*x = SessionState{}
	mi := &file_api_proto_common_yagpcc_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionState) ProtoMessage() {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_common_yagpcc_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionState.ProtoReflect.Descriptor instead.
func (*SessionState) Descriptor() ([]byte, []int) {
	return file_api_proto_common_yagpcc_session_proto_rawDescGZIP(), []int{3}
}

func (x *SessionState) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *SessionState) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *SessionState) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SessionState) GetSessionKey() *SessionKey {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *SessionState) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

func (x *SessionState) GetRunningQuery() *QueryKey {
	if x != nil {
		return x.RunningQuery
	}
	return nil
}

func (x *SessionState) GetRunningQueryInfo() *QueryInfo {
	if x != nil {
		return x.RunningQueryInfo
	}
	return nil
}

func (x *SessionState) GetRunningQueryStatus() QueryStatus {
	if x != nil {
		return x.RunningQueryStatus
	}
	return QueryStatus_QUERY_STATUS_UNSPECIFIED
}

func (x *SessionState) GetTotalMetrics() *GPMetrics {
	if x != nil {
		return x.TotalMetrics
	}
	return nil
}

func (x *SessionState) GetLastMetrics() *GPMetrics {
	if x != nil {
		return x.LastMetrics
	}
	return nil
}

func (x *SessionState) GetQueryMetrics() *GPMetrics {
	if x != nil {
		return x.QueryMetrics
	}
	return nil
}

func (x *SessionState) GetRunningQueryLevel() int64 {
	if x != nil {
		return x.RunningQueryLevel
	}
	return 0
}

func (x *SessionState) GetRunningQueriesStack() []*QueryDesc {
	if x != nil {
		return x.RunningQueriesStack
	}
	return nil
}

func (x *SessionState) GetBlockedSessionLevel() int64 {
	if x != nil {
		return x.BlockedSessionLevel
	}
	return 0
}

func (x *SessionState) GetRunningQueryError() string {
	if x != nil {
		return x.RunningQueryError
	}
	return ""
}

func (x *SessionState) GetRunningQuerySlices() int64 {
	if x != nil {
		return x.RunningQuerySlices
	}
	return 0
}

var File_api_proto_common_yagpcc_session_proto protoreflect.FileDescriptor

const file_api_proto_common_yagpcc_session_proto_rawDesc = "" +
	"\n" +
	"%api/proto/common/yagpcc_session.proto\x12\x06yagpcc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%api/proto/common/yagpcc_metrics.proto\":\n" +
	"\n" +
	"SessionKey\x12\x17\n" +
	"\asess_id\x18\x01 \x01(\x03R\x06sessId\x12\x13\n" +
	"\x05tm_id\x18\x02 \x01(\x03R\x04tmId\"\xe0\x06\n" +
	"\vSessionInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x03R\x03pid\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12)\n" +
	"\x10application_name\x18\x04 \x01(\tR\x0fapplicationName\x12\x1f\n" +
	"\vclient_addr\x18\x05 \x01(\tR\n" +
	"clientAddr\x12'\n" +
	"\x0fclient_hostname\x18\x06 \x01(\tR\x0eclientHostname\x12\x1f\n" +
	"\vclient_port\x18\a \x01(\x03R\n" +
	"clientPort\x12?\n" +
	"\rbackend_start\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fbackendStart\x129\n" +
	"\n" +
	"xact_start\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\txactStart\x12;\n" +
	"\vquery_start\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"queryStart\x12=\n" +
	"\fstate_change\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vstateChange\x12%\n" +
	"\x0ewaiting_reason\x18\f \x01(\tR\rwaitingReason\x12\x18\n" +
	"\awaiting\x18\r \x01(\bR\awaiting\x12\x14\n" +
	"\x05state\x18\x0e \x01(\tR\x05state\x12\x1f\n" +
	"\vbackend_xid\x18\x0f \x01(\tR\n" +
	"backendXid\x12!\n" +
	"\fbackend_xmin\x18\x10 \x01(\tR\vbackendXmin\x12\x14\n" +
	"\x05rsgid\x18\x11 \x01(\x03R\x05rsgid\x12\x18\n" +
	"\arsgname\x18\x12 \x01(\tR\arsgname\x12*\n" +
	"\x10rsgqueueduration\x18\x13 \x01(\tR\x10rsgqueueduration\x12+\n" +
	"\x12blocked_by_sess_id\x18\x14 \x01(\x03R\x0fblockedBySessId\x12\x1b\n" +
	"\twait_mode\x18\x15 \x01(\tR\bwaitMode\x12\x1f\n" +
	"\vlocked_item\x18\x16 \x01(\tR\n" +
	"lockedItem\x12\x1f\n" +
	"\vlocked_mode\x18\x17 \x01(\tR\n" +
	"lockedMode\"\x82\x02\n" +
	"\tQueryDesc\x12-\n" +
	"\tquery_key\x18\x01 \x01(\v2\x10.yagpcc.QueryKeyR\bqueryKey\x120\n" +
	"\n" +
	"query_info\x18\x02 \x01(\v2\x11.yagpcc.QueryInfoR\tqueryInfo\x126\n" +
	"\fquery_status\x18\x03 \x01(\x0e2\x13.yagpcc.QueryStatusR\vqueryStatus\x12\x1f\n" +
	"\vquery_level\x18\x04 \x01(\x03R\n" +
	"queryLevel\x12;\n" +
	"\vquery_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"queryStart\"\xd8\x06\n" +
	"\fSessionState\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x123\n" +
	"\vsession_key\x18\x04 \x01(\v2\x12.yagpcc.SessionKeyR\n" +
	"sessionKey\x126\n" +
	"\fsession_info\x18\x05 \x01(\v2\x13.yagpcc.SessionInfoR\vsessionInfo\x125\n" +
	"\rrunning_query\x18\x06 \x01(\v2\x10.yagpcc.QueryKeyR\frunningQuery\x12?\n" +
	"\x12running_query_info\x18\a \x01(\v2\x11.yagpcc.QueryInfoR\x10runningQueryInfo\x12E\n" +
	"\x14running_query_status\x18\b \x01(\x0e2\x13.yagpcc.QueryStatusR\x12runningQueryStatus\x126\n" +
	"\rtotal_metrics\x18\t \x01(\v2\x11.yagpcc.GPMetricsR\ftotalMetrics\x124\n" +
	"\flast_metrics\x18\n" +
	" \x01(\v2\x11.yagpcc.GPMetricsR\vlastMetrics\x126\n" +
	"\rquery_metrics\x18\v \x01(\v2\x11.yagpcc.GPMetricsR\fqueryMetrics\x12.\n" +
	"\x13running_query_level\x18\f \x01(\x03R\x11runningQueryLevel\x12E\n" +
	"\x15running_queries_stack\x18\r \x03(\v2\x11.yagpcc.QueryDescR\x13runningQueriesStack\x122\n" +
	"\x15blocked_session_level\x18\x0e \x01(\x03R\x13blockedSessionLevel\x12.\n" +
	"\x13running_query_error\x18\x0f \x01(\tR\x11runningQueryError\x120\n" +
	"\x14running_query_slices\x18\x10 \x01(\x03R\x12runningQuerySlicesBGB\rMasterYAGPCCMZ6github.com/open-gpdb/yagpcc/api/proto/common;greenplumb\x06proto3"

var (
	file_api_proto_common_yagpcc_session_proto_rawDescOnce sync.Once
	file_api_proto_common_yagpcc_session_proto_rawDescData []byte
)

func file_api_proto_common_yagpcc_session_proto_rawDescGZIP() []byte {
	file_api_proto_common_yagpcc_session_proto_rawDescOnce.Do(func() {
		file_api_proto_common_yagpcc_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_common_yagpcc_session_proto_rawDesc), len(file_api_proto_common_yagpcc_session_proto_rawDesc)))
	})
	return file_api_proto_common_yagpcc_session_proto_rawDescData
}

var file_api_proto_common_yagpcc_session_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_common_yagpcc_session_proto_goTypes = []any{
	(*SessionKey)(nil),            // 0: yagpcc.SessionKey
	(*SessionInfo)(nil),           // 1: yagpcc.SessionInfo
	(*QueryDesc)(nil),             // 2: yagpcc.QueryDesc
	(*SessionState)(nil),          // 3: yagpcc.SessionState
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*QueryKey)(nil),              // 5: yagpcc.QueryKey
	(*QueryInfo)(nil),             // 6: yagpcc.QueryInfo
	(QueryStatus)(0),              // 7: yagpcc.QueryStatus
	(*GPMetrics)(nil),             // 8: yagpcc.GPMetrics
}
var file_api_proto_common_yagpcc_session_proto_depIdxs = []int32{
	4,  // 0: yagpcc.SessionInfo.backend_start:type_name -> google.protobuf.Timestamp
	4,  // 1: yagpcc.SessionInfo.xact_start:type_name -> google.protobuf.Timestamp
	4,  // 2: yagpcc.SessionInfo.query_start:type_name -> google.protobuf.Timestamp
	4,  // 3: yagpcc.SessionInfo.state_change:type_name -> google.protobuf.Timestamp
	5,  // 4: yagpcc.QueryDesc.query_key:type_name -> yagpcc.QueryKey
	6,  // 5: yagpcc.QueryDesc.query_info:type_name -> yagpcc.QueryInfo
	7,  // 6: yagpcc.QueryDesc.query_status:type_name -> yagpcc.QueryStatus
	4,  // 7: yagpcc.QueryDesc.query_start:type_name -> google.protobuf.Timestamp
	4,  // 8: yagpcc.SessionState.time:type_name -> google.protobuf.Timestamp
	0,  // 9: yagpcc.SessionState.session_key:type_name -> yagpcc.SessionKey
	1,  // 10: yagpcc.SessionState.session_info:type_name -> yagpcc.SessionInfo
	5,  // 11: yagpcc.SessionState.running_query:type_name -> yagpcc.QueryKey
	6,  // 12: yagpcc.SessionState.running_query_info:type_name -> yagpcc.QueryInfo
	7,  // 13: yagpcc.SessionState.running_query_status:type_name -> yagpcc.QueryStatus
	8,  // 14: yagpcc.SessionState.total_metrics:type_name -> yagpcc.GPMetrics
	8,  // 15: yagpcc.SessionState.last_metrics:type_name -> yagpcc.GPMetrics
	8,  // 16: yagpcc.SessionState.query_metrics:type_name -> yagpcc.GPMetrics
	2,  // 17: yagpcc.SessionState.running_queries_stack:type_name -> yagpcc.QueryDesc
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_proto_common_yagpcc_session_proto_init() }
func file_api_proto_common_yagpcc_session_proto_init() {
	if File_api_proto_common_yagpcc_session_proto != nil {
		return
	}
	file_api_proto_common_yagpcc_metrics_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_common_yagpcc_session_proto_rawDesc), len(file_api_proto_common_yagpcc_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_common_yagpcc_session_proto_goTypes,
		DependencyIndexes: file_api_proto_common_yagpcc_session_proto_depIdxs,
		MessageInfos:      file_api_proto_common_yagpcc_session_proto_msgTypes,
	}.Build()
	File_api_proto_common_yagpcc_session_proto = out.File
	file_api_proto_common_yagpcc_session_proto_goTypes = nil
	file_api_proto_common_yagpcc_session_proto_depIdxs = nil
}
