// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package uds_test is a generated GoMock package.
package uds_test

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	greenplum "github.com/open-gpdb/yagpcc/api/proto/agent_segment"
)

// MockLogger is a mock of logger interface
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// MockConnection is a mock of connection interface
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
}

// MockConnectionMockRecorder is the mock recorder for MockConnection
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	mock := &MockConnection{ctrl: ctrl}
	mock.recorder = &MockConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	return m.recorder
}

// SetReadDeadline mocks base method
func (m *MockConnection) SetReadDeadline(t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReadDeadline", t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReadDeadline indicates an expected call of SetReadDeadline
func (mr *MockConnectionMockRecorder) SetReadDeadline(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReadDeadline", reflect.TypeOf((*MockConnection)(nil).SetReadDeadline), t)
}

// Read mocks base method
func (m *MockConnection) Read(b []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", b)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockConnectionMockRecorder) Read(b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockConnection)(nil).Read), b)
}

// Close mocks base method
func (m *MockConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConnection)(nil).Close))
}

// MockSetQIServer is a mock of setQIServer interface
type MockSetQIServer struct {
	ctrl     *gomock.Controller
	recorder *MockSetQIServerMockRecorder
}

// MockSetQIServerMockRecorder is the mock recorder for MockSetQIServer
type MockSetQIServerMockRecorder struct {
	mock *MockSetQIServer
}

// NewMockSetQIServer creates a new mock instance
func NewMockSetQIServer(ctrl *gomock.Controller) *MockSetQIServer {
	mock := &MockSetQIServer{ctrl: ctrl}
	mock.recorder = &MockSetQIServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSetQIServer) EXPECT() *MockSetQIServerMockRecorder {
	return m.recorder
}

// SetMetricQuery mocks base method
func (m *MockSetQIServer) SetMetricQuery(ctx context.Context, in *greenplum.SetQueryReq) (*greenplum.MetricResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMetricQuery", ctx, in)
	ret0, _ := ret[0].(*greenplum.MetricResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMetricQuery indicates an expected call of SetMetricQuery
func (mr *MockSetQIServerMockRecorder) SetMetricQuery(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetricQuery", reflect.TypeOf((*MockSetQIServer)(nil).SetMetricQuery), ctx, in)
}
