// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package stat_activity_test is a generated GoMock package.
package stat_activity_test

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockLog is a mock of log interface
type MockLog struct {
	ctrl     *gomock.Controller
	recorder *MockLogMockRecorder
}

// MockLogMockRecorder is the mock recorder for MockLog
type MockLogMockRecorder struct {
	mock *MockLog
}

// NewMockLog creates a new mock instance
func NewMockLog(ctrl *gomock.Controller) *MockLog {
	mock := &MockLog{ctrl: ctrl}
	mock.recorder = &MockLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLog) EXPECT() *MockLogMockRecorder {
	return m.recorder
}

// Infof mocks base method
func (m *MockLog) Infof(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof
func (mr *MockLogMockRecorder) Infof(format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLog)(nil).Infof), varargs...)
}

// Warnf mocks base method
func (m *MockLog) Warnf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf
func (mr *MockLogMockRecorder) Warnf(format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLog)(nil).Warnf), varargs...)
}

// MockDB is a mock of db interface
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// ExecQuery mocks base method
func (m *MockDB) ExecQuery(ctx context.Context, query string, dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecQuery", ctx, query, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecQuery indicates an expected call of ExecQuery
func (mr *MockDBMockRecorder) ExecQuery(ctx, query, dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecQuery", reflect.TypeOf((*MockDB)(nil).ExecQuery), ctx, query, dest)
}

// MockMetricsProvider is a mock of metricsProvider interface
type MockMetricsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsProviderMockRecorder
}

// MockMetricsProviderMockRecorder is the mock recorder for MockMetricsProvider
type MockMetricsProviderMockRecorder struct {
	mock *MockMetricsProvider
}

// NewMockMetricsProvider creates a new mock instance
func NewMockMetricsProvider(ctrl *gomock.Controller) *MockMetricsProvider {
	mock := &MockMetricsProvider{ctrl: ctrl}
	mock.recorder = &MockMetricsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMetricsProvider) EXPECT() *MockMetricsProviderMockRecorder {
	return m.recorder
}

// MockMetricsTimeVec is a mock of metricsTimeVec interface
type MockMetricsTimeVec struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsTimeVecMockRecorder
}

// MockMetricsTimeVecMockRecorder is the mock recorder for MockMetricsTimeVec
type MockMetricsTimeVecMockRecorder struct {
	mock *MockMetricsTimeVec
}

// NewMockMetricsTimeVec creates a new mock instance
func NewMockMetricsTimeVec(ctrl *gomock.Controller) *MockMetricsTimeVec {
	mock := &MockMetricsTimeVec{ctrl: ctrl}
	mock.recorder = &MockMetricsTimeVecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMetricsTimeVec) EXPECT() *MockMetricsTimeVecMockRecorder {
	return m.recorder
}

// With indicates an expected call of With
func (mr *MockMetricsTimeVecMockRecorder) With(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*MockMetricsTimeVec)(nil)), arg0)
}

// Reset mocks base method
func (m *MockMetricsTimeVec) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset
func (mr *MockMetricsTimeVecMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockMetricsTimeVec)(nil).Reset))
}

// MockMetricsTimer is a mock of metricsTimer interface
type MockMetricsTimer struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsTimerMockRecorder
}

// MockMetricsTimerMockRecorder is the mock recorder for MockMetricsTimer
type MockMetricsTimerMockRecorder struct {
	mock *MockMetricsTimer
}

// NewMockMetricsTimer creates a new mock instance
func NewMockMetricsTimer(ctrl *gomock.Controller) *MockMetricsTimer {
	mock := &MockMetricsTimer{ctrl: ctrl}
	mock.recorder = &MockMetricsTimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMetricsTimer) EXPECT() *MockMetricsTimerMockRecorder {
	return m.recorder
}

// RecordDuration mocks base method
func (m *MockMetricsTimer) RecordDuration(value time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDuration", value)
}

// RecordDuration indicates an expected call of RecordDuration
func (mr *MockMetricsTimerMockRecorder) RecordDuration(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDuration", reflect.TypeOf((*MockMetricsTimer)(nil).RecordDuration), value)
}
