// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go

// Package grpc_test is a generated GoMock package.
package grpc_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gp "github.com/open-gpdb/yagpcc/internal/gp"
)

// MockStatActivityLister is a mock of statActivityLister interface
type MockStatActivityLister struct {
	ctrl     *gomock.Controller
	recorder *MockStatActivityListerMockRecorder
}

// MockStatActivityListerMockRecorder is the mock recorder for MockStatActivityLister
type MockStatActivityListerMockRecorder struct {
	mock *MockStatActivityLister
}

// NewMockStatActivityLister creates a new mock instance
func NewMockStatActivityLister(ctrl *gomock.Controller) *MockStatActivityLister {
	mock := &MockStatActivityLister{ctrl: ctrl}
	mock.recorder = &MockStatActivityListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStatActivityLister) EXPECT() *MockStatActivityListerMockRecorder {
	return m.recorder
}

// Start mocks base method
func (m *MockStatActivityLister) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start
func (mr *MockStatActivityListerMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockStatActivityLister)(nil).Start), ctx)
}

// Stop mocks base method
func (m *MockStatActivityLister) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop
func (mr *MockStatActivityListerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockStatActivityLister)(nil).Stop))
}

// List mocks base method
func (m *MockStatActivityLister) List(ctx context.Context) ([]*gp.GpStatActivity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*gp.GpStatActivity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockStatActivityListerMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStatActivityLister)(nil).List), ctx)
}
