// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/agent_segment/yagpcc_get_service.proto

package greenplum

import (
	common "github.com/open-gpdb/yagpcc/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryData struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	QueryStatus    common.QueryStatus          `protobuf:"varint,1,opt,name=query_status,json=queryStatus,proto3,enum=yagpcc.QueryStatus" json:"query_status,omitempty"`
	QueryStart     *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=query_start,json=queryStart,proto3" json:"query_start,omitempty"`
	QueryEnd       *timestamppb.Timestamp      `protobuf:"bytes,3,opt,name=query_end,json=queryEnd,proto3" json:"query_end,omitempty"`
	QueryKey       *common.QueryKey            `protobuf:"bytes,4,opt,name=query_key,json=queryKey,proto3" json:"query_key,omitempty"`
	SegmentKey     *common.SegmentKey          `protobuf:"bytes,5,opt,name=segment_key,json=segmentKey,proto3" json:"segment_key,omitempty"`
	QueryInfo      *common.QueryInfo           `protobuf:"bytes,6,opt,name=query_info,json=queryInfo,proto3" json:"query_info,omitempty"`
	QueryMetrics   *common.GPMetrics           `protobuf:"bytes,7,opt,name=query_metrics,json=queryMetrics,proto3" json:"query_metrics,omitempty"`
	AdditionalStat *common.AdditionalQueryStat `protobuf:"bytes,9,opt,name=additional_stat,json=additionalStat,proto3" json:"additional_stat,omitempty"`
	SliceId        int64                       `protobuf:"varint,10,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryData) Reset() {
	*x = QueryData{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryData) ProtoMessage() {}

func (x *QueryData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryData.ProtoReflect.Descriptor instead.
func (*QueryData) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryData) GetQueryStatus() common.QueryStatus {
	if x != nil {
		return x.QueryStatus
	}
	return common.QueryStatus(0)
}

func (x *QueryData) GetQueryStart() *timestamppb.Timestamp {
	if x != nil {
		return x.QueryStart
	}
	return nil
}

func (x *QueryData) GetQueryEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.QueryEnd
	}
	return nil
}

func (x *QueryData) GetQueryKey() *common.QueryKey {
	if x != nil {
		return x.QueryKey
	}
	return nil
}

func (x *QueryData) GetSegmentKey() *common.SegmentKey {
	if x != nil {
		return x.SegmentKey
	}
	return nil
}

func (x *QueryData) GetQueryInfo() *common.QueryInfo {
	if x != nil {
		return x.QueryInfo
	}
	return nil
}

func (x *QueryData) GetQueryMetrics() *common.GPMetrics {
	if x != nil {
		return x.QueryMetrics
	}
	return nil
}

func (x *QueryData) GetAdditionalStat() *common.AdditionalQueryStat {
	if x != nil {
		return x.AdditionalStat
	}
	return nil
}

func (x *QueryData) GetSliceId() int64 {
	if x != nil {
		return x.SliceId
	}
	return 0
}

type GetQueriesInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueriesData   []*QueryData           `protobuf:"bytes,1,rep,name=queries_data,json=queriesData,proto3" json:"queries_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueriesInfoResponse) Reset() {
	*x = GetQueriesInfoResponse{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueriesInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueriesInfoResponse) ProtoMessage() {}

func (x *GetQueriesInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueriesInfoResponse.ProtoReflect.Descriptor instead.
func (*GetQueriesInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetQueriesInfoResponse) GetQueriesData() []*QueryData {
	if x != nil {
		return x.QueriesData
	}
	return nil
}

type GetQueriesInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterQueries []*common.QueryKey     `protobuf:"bytes,1,rep,name=filter_queries,json=filterQueries,proto3" json:"filter_queries,omitempty"` // if set show queries with specific QueryKey's
	FromTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`                // if set filter out entries with query start before from_time
	ToTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`                      // if set filter out entries with query end after to_time
	ClearSent     bool                   `protobuf:"varint,4,opt,name=clear_sent,json=clearSent,proto3" json:"clear_sent,omitempty"`            // clear info after sent query data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueriesInfoReq) Reset() {
	*x = GetQueriesInfoReq{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueriesInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueriesInfoReq) ProtoMessage() {}

func (x *GetQueriesInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueriesInfoReq.ProtoReflect.Descriptor instead.
func (*GetQueriesInfoReq) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetQueriesInfoReq) GetFilterQueries() []*common.QueryKey {
	if x != nil {
		return x.FilterQueries
	}
	return nil
}

func (x *GetQueriesInfoReq) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *GetQueriesInfoReq) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

func (x *GetQueriesInfoReq) GetClearSent() bool {
	if x != nil {
		return x.ClearSent
	}
	return false
}

var File_api_proto_agent_segment_yagpcc_get_service_proto protoreflect.FileDescriptor

const file_api_proto_agent_segment_yagpcc_get_service_proto_rawDesc = "" +
	"\n" +
	"0api/proto/agent_segment/yagpcc_get_service.proto\x12\x06yagpcc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%api/proto/common/yagpcc_metrics.proto\"\xe8\x03\n" +
	"\tQueryData\x126\n" +
	"\fquery_status\x18\x01 \x01(\x0e2\x13.yagpcc.QueryStatusR\vqueryStatus\x12;\n" +
	"\vquery_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"queryStart\x127\n" +
	"\tquery_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bqueryEnd\x12-\n" +
	"\tquery_key\x18\x04 \x01(\v2\x10.yagpcc.QueryKeyR\bqueryKey\x123\n" +
	"\vsegment_key\x18\x05 \x01(\v2\x12.yagpcc.SegmentKeyR\n" +
	"segmentKey\x120\n" +
	"\n" +
	"query_info\x18\x06 \x01(\v2\x11.yagpcc.QueryInfoR\tqueryInfo\x126\n" +
	"\rquery_metrics\x18\a \x01(\v2\x11.yagpcc.GPMetricsR\fqueryMetrics\x12D\n" +
	"\x0fadditional_stat\x18\t \x01(\v2\x1b.yagpcc.AdditionalQueryStatR\x0eadditionalStat\x12\x19\n" +
	"\bslice_id\x18\n" +
	" \x01(\x03R\asliceId\"N\n" +
	"\x16GetQueriesInfoResponse\x124\n" +
	"\fqueries_data\x18\x01 \x03(\v2\x11.yagpcc.QueryDataR\vqueriesData\"\xd9\x01\n" +
	"\x11GetQueriesInfoReq\x127\n" +
	"\x0efilter_queries\x18\x01 \x03(\v2\x10.yagpcc.QueryKeyR\rfilterQueries\x127\n" +
	"\tfrom_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bfromTime\x123\n" +
	"\ato_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06toTime\x12\x1d\n" +
	"\n" +
	"clear_sent\x18\x04 \x01(\bR\tclearSent2_\n" +
	"\fGetQueryInfo\x12O\n" +
	"\x10GetMetricQueries\x12\x19.yagpcc.GetQueriesInfoReq\x1a\x1e.yagpcc.GetQueriesInfoResponse\"\x00BPB\x0fSegmentYAGPCCAGZ=github.com/open-gpdb/yagpcc/api/proto/agent_segment;greenplumb\x06proto3"

var (
	file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescOnce sync.Once
	file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescData []byte
)

func file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP() []byte {
	file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_segment_yagpcc_get_service_proto_rawDesc), len(file_api_proto_agent_segment_yagpcc_get_service_proto_rawDesc)))
	})
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescData
}

var file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_agent_segment_yagpcc_get_service_proto_goTypes = []any{
	(*QueryData)(nil),                  // 0: yagpcc.QueryData
	(*GetQueriesInfoResponse)(nil),     // 1: yagpcc.GetQueriesInfoResponse
	(*GetQueriesInfoReq)(nil),          // 2: yagpcc.GetQueriesInfoReq
	(common.QueryStatus)(0),            // 3: yagpcc.QueryStatus
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
	(*common.QueryKey)(nil),            // 5: yagpcc.QueryKey
	(*common.SegmentKey)(nil),          // 6: yagpcc.SegmentKey
	(*common.QueryInfo)(nil),           // 7: yagpcc.QueryInfo
	(*common.GPMetrics)(nil),           // 8: yagpcc.GPMetrics
	(*common.AdditionalQueryStat)(nil), // 9: yagpcc.AdditionalQueryStat
}
var file_api_proto_agent_segment_yagpcc_get_service_proto_depIdxs = []int32{
	3,  // 0: yagpcc.QueryData.query_status:type_name -> yagpcc.QueryStatus
	4,  // 1: yagpcc.QueryData.query_start:type_name -> google.protobuf.Timestamp
	4,  // 2: yagpcc.QueryData.query_end:type_name -> google.protobuf.Timestamp
	5,  // 3: yagpcc.QueryData.query_key:type_name -> yagpcc.QueryKey
	6,  // 4: yagpcc.QueryData.segment_key:type_name -> yagpcc.SegmentKey
	7,  // 5: yagpcc.QueryData.query_info:type_name -> yagpcc.QueryInfo
	8,  // 6: yagpcc.QueryData.query_metrics:type_name -> yagpcc.GPMetrics
	9,  // 7: yagpcc.QueryData.additional_stat:type_name -> yagpcc.AdditionalQueryStat
	0,  // 8: yagpcc.GetQueriesInfoResponse.queries_data:type_name -> yagpcc.QueryData
	5,  // 9: yagpcc.GetQueriesInfoReq.filter_queries:type_name -> yagpcc.QueryKey
	4,  // 10: yagpcc.GetQueriesInfoReq.from_time:type_name -> google.protobuf.Timestamp
	4,  // 11: yagpcc.GetQueriesInfoReq.to_time:type_name -> google.protobuf.Timestamp
	2,  // 12: yagpcc.GetQueryInfo.GetMetricQueries:input_type -> yagpcc.GetQueriesInfoReq
	1,  // 13: yagpcc.GetQueryInfo.GetMetricQueries:output_type -> yagpcc.GetQueriesInfoResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_agent_segment_yagpcc_get_service_proto_init() }
func file_api_proto_agent_segment_yagpcc_get_service_proto_init() {
	if File_api_proto_agent_segment_yagpcc_get_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_segment_yagpcc_get_service_proto_rawDesc), len(file_api_proto_agent_segment_yagpcc_get_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_segment_yagpcc_get_service_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_segment_yagpcc_get_service_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes,
	}.Build()
	File_api_proto_agent_segment_yagpcc_get_service_proto = out.File
	file_api_proto_agent_segment_yagpcc_get_service_proto_goTypes = nil
	file_api_proto_agent_segment_yagpcc_get_service_proto_depIdxs = nil
}
