// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/agent_segment/yagpcc_control_service.proto

package greenplum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlResponseStatusCode int32

const (
	ControlResponseStatusCode_CONTROL_RESPONSE_STATUS_CODE_UNSPECIFIED ControlResponseStatusCode = 0
	ControlResponseStatusCode_CONTROL_RESPONSE_STATUS_CODE_SUCCESS     ControlResponseStatusCode = 1
	ControlResponseStatusCode_CONTROL_RESPONSE_STATUS_CODE_ERROR       ControlResponseStatusCode = 2
)

// Enum value maps for ControlResponseStatusCode.
var (
	ControlResponseStatusCode_name = map[int32]string{
		0: "CONTROL_RESPONSE_STATUS_CODE_UNSPECIFIED",
		1: "CONTROL_RESPONSE_STATUS_CODE_SUCCESS",
		2: "CONTROL_RESPONSE_STATUS_CODE_ERROR",
	}
	ControlResponseStatusCode_value = map[string]int32{
		"CONTROL_RESPONSE_STATUS_CODE_UNSPECIFIED": 0,
		"CONTROL_RESPONSE_STATUS_CODE_SUCCESS":     1,
		"CONTROL_RESPONSE_STATUS_CODE_ERROR":       2,
	}
)

func (x ControlResponseStatusCode) Enum() *ControlResponseStatusCode {
	p := new(ControlResponseStatusCode)
	*p = x
	return p
}

func (x ControlResponseStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlResponseStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_agent_segment_yagpcc_control_service_proto_enumTypes[0].Descriptor()
}

func (ControlResponseStatusCode) Type() protoreflect.EnumType {
	return &file_api_proto_agent_segment_yagpcc_control_service_proto_enumTypes[0]
}

func (x ControlResponseStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlResponseStatusCode.Descriptor instead.
func (ControlResponseStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_control_service_proto_rawDescGZIP(), []int{0}
}

type ResetStatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetStatReq) Reset() {
	*x = ResetStatReq{}
	mi := &file_api_proto_agent_segment_yagpcc_control_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetStatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetStatReq) ProtoMessage() {}

func (x *ResetStatReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_control_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetStatReq.ProtoReflect.Descriptor instead.
func (*ResetStatReq) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_control_service_proto_rawDescGZIP(), []int{0}
}

type GetInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoReq) Reset() {
	*x = GetInfoReq{}
	mi := &file_api_proto_agent_segment_yagpcc_control_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoReq) ProtoMessage() {}

func (x *GetInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_control_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoReq.ProtoReflect.Descriptor instead.
func (*GetInfoReq) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_control_service_proto_rawDescGZIP(), []int{1}
}

type InfoRepsonse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ResetTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=reset_time,json=resetTime,proto3" json:"reset_time,omitempty"`
	QueriesCount    uint64                 `protobuf:"varint,3,opt,name=queries_count,json=queriesCount,proto3" json:"queries_count,omitempty"`
	PlannodesCount  uint64                 `protobuf:"varint,4,opt,name=plannodes_count,json=plannodesCount,proto3" json:"plannodes_count,omitempty"`
	QueriesWipedOut uint64                 `protobuf:"varint,5,opt,name=queries_wiped_out,json=queriesWipedOut,proto3" json:"queries_wiped_out,omitempty"`
	PlansWipedOut   uint64                 `protobuf:"varint,6,opt,name=plans_wiped_out,json=plansWipedOut,proto3" json:"plans_wiped_out,omitempty"`
	NumGc           uint64                 `protobuf:"varint,7,opt,name=num_gc,json=numGc,proto3" json:"num_gc,omitempty"`
	HeapInuse       uint64                 `protobuf:"varint,8,opt,name=heap_inuse,json=heapInuse,proto3" json:"heap_inuse,omitempty"`
	HeapAlloc       uint64                 `protobuf:"varint,9,opt,name=heap_alloc,json=heapAlloc,proto3" json:"heap_alloc,omitempty"`
	NumSysGc        uint32                 `protobuf:"varint,10,opt,name=num_sys_gc,json=numSysGc,proto3" json:"num_sys_gc,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InfoRepsonse) Reset() {
	*x = InfoRepsonse{}
	mi := &file_api_proto_agent_segment_yagpcc_control_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRepsonse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRepsonse) ProtoMessage() {}

func (x *InfoRepsonse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_control_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRepsonse.ProtoReflect.Descriptor instead.
func (*InfoRepsonse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_control_service_proto_rawDescGZIP(), []int{2}
}

func (x *InfoRepsonse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoRepsonse) GetResetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ResetTime
	}
	return nil
}

func (x *InfoRepsonse) GetQueriesCount() uint64 {
	if x != nil {
		return x.QueriesCount
	}
	return 0
}

func (x *InfoRepsonse) GetPlannodesCount() uint64 {
	if x != nil {
		return x.PlannodesCount
	}
	return 0
}

func (x *InfoRepsonse) GetQueriesWipedOut() uint64 {
	if x != nil {
		return x.QueriesWipedOut
	}
	return 0
}

func (x *InfoRepsonse) GetPlansWipedOut() uint64 {
	if x != nil {
		return x.PlansWipedOut
	}
	return 0
}

func (x *InfoRepsonse) GetNumGc() uint64 {
	if x != nil {
		return x.NumGc
	}
	return 0
}

func (x *InfoRepsonse) GetHeapInuse() uint64 {
	if x != nil {
		return x.HeapInuse
	}
	return 0
}

func (x *InfoRepsonse) GetHeapAlloc() uint64 {
	if x != nil {
		return x.HeapAlloc
	}
	return 0
}

func (x *InfoRepsonse) GetNumSysGc() uint32 {
	if x != nil {
		return x.NumSysGc
	}
	return 0
}

type ControlResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ErrorCode     ControlResponseStatusCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=yagpcc.ControlResponseStatusCode" json:"error_code,omitempty"`
	ErrorText     string                    `protobuf:"bytes,2,opt,name=error_text,json=errorText,proto3" json:"error_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_api_proto_agent_segment_yagpcc_control_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_control_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_control_service_proto_rawDescGZIP(), []int{3}
}

func (x *ControlResponse) GetErrorCode() ControlResponseStatusCode {
	if x != nil {
		return x.ErrorCode
	}
	return ControlResponseStatusCode_CONTROL_RESPONSE_STATUS_CODE_UNSPECIFIED
}

func (x *ControlResponse) GetErrorText() string {
	if x != nil {
		return x.ErrorText
	}
	return ""
}

var File_api_proto_agent_segment_yagpcc_control_service_proto protoreflect.FileDescriptor

const file_api_proto_agent_segment_yagpcc_control_service_proto_rawDesc = "" +
	"\n" +
	"4api/proto/agent_segment/yagpcc_control_service.proto\x12\x06yagpcc\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fResetStatReq\"\f\n" +
	"\n" +
	"GetInfoReq\"\xf8\x02\n" +
	"\fInfoRepsonse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x129\n" +
	"\n" +
	"reset_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tresetTime\x12#\n" +
	"\rqueries_count\x18\x03 \x01(\x04R\fqueriesCount\x12'\n" +
	"\x0fplannodes_count\x18\x04 \x01(\x04R\x0eplannodesCount\x12*\n" +
	"\x11queries_wiped_out\x18\x05 \x01(\x04R\x0fqueriesWipedOut\x12&\n" +
	"\x0fplans_wiped_out\x18\x06 \x01(\x04R\rplansWipedOut\x12\x15\n" +
	"\x06num_gc\x18\a \x01(\x04R\x05numGc\x12\x1d\n" +
	"\n" +
	"heap_inuse\x18\b \x01(\x04R\theapInuse\x12\x1d\n" +
	"\n" +
	"heap_alloc\x18\t \x01(\x04R\theapAlloc\x12\x1c\n" +
	"\n" +
	"num_sys_gc\x18\n" +
	" \x01(\rR\bnumSysGc\"r\n" +
	"\x0fControlResponse\x12@\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2!.yagpcc.ControlResponseStatusCodeR\terrorCode\x12\x1d\n" +
	"\n" +
	"error_text\x18\x02 \x01(\tR\terrorText*\x9b\x01\n" +
	"\x19ControlResponseStatusCode\x12,\n" +
	"(CONTROL_RESPONSE_STATUS_CODE_UNSPECIFIED\x10\x00\x12(\n" +
	"$CONTROL_RESPONSE_STATUS_CODE_SUCCESS\x10\x01\x12&\n" +
	"\"CONTROL_RESPONSE_STATUS_CODE_ERROR\x10\x022\x88\x01\n" +
	"\fAgentControl\x12<\n" +
	"\tResetStat\x12\x14.yagpcc.ResetStatReq\x1a\x17.yagpcc.ControlResponse\"\x00\x12:\n" +
	"\fGetAgentInfo\x12\x12.yagpcc.GetInfoReq\x1a\x14.yagpcc.InfoRepsonse\"\x00BPB\x0fSegmentYAGPCCACZ=github.com/open-gpdb/yagpcc/api/proto/agent_segment;greenplumb\x06proto3"

var (
	file_api_proto_agent_segment_yagpcc_control_service_proto_rawDescOnce sync.Once
	file_api_proto_agent_segment_yagpcc_control_service_proto_rawDescData []byte
)

func file_api_proto_agent_segment_yagpcc_control_service_proto_rawDescGZIP() []byte {
	file_api_proto_agent_segment_yagpcc_control_service_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_segment_yagpcc_control_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_segment_yagpcc_control_service_proto_rawDesc), len(file_api_proto_agent_segment_yagpcc_control_service_proto_rawDesc)))
	})
	return file_api_proto_agent_segment_yagpcc_control_service_proto_rawDescData
}

var file_api_proto_agent_segment_yagpcc_control_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_agent_segment_yagpcc_control_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_agent_segment_yagpcc_control_service_proto_goTypes = []any{
	(ControlResponseStatusCode)(0), // 0: yagpcc.ControlResponseStatusCode
	(*ResetStatReq)(nil),           // 1: yagpcc.ResetStatReq
	(*GetInfoReq)(nil),             // 2: yagpcc.GetInfoReq
	(*InfoRepsonse)(nil),           // 3: yagpcc.InfoRepsonse
	(*ControlResponse)(nil),        // 4: yagpcc.ControlResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_api_proto_agent_segment_yagpcc_control_service_proto_depIdxs = []int32{
	5, // 0: yagpcc.InfoRepsonse.reset_time:type_name -> google.protobuf.Timestamp
	0, // 1: yagpcc.ControlResponse.error_code:type_name -> yagpcc.ControlResponseStatusCode
	1, // 2: yagpcc.AgentControl.ResetStat:input_type -> yagpcc.ResetStatReq
	2, // 3: yagpcc.AgentControl.GetAgentInfo:input_type -> yagpcc.GetInfoReq
	4, // 4: yagpcc.AgentControl.ResetStat:output_type -> yagpcc.ControlResponse
	3, // 5: yagpcc.AgentControl.GetAgentInfo:output_type -> yagpcc.InfoRepsonse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_agent_segment_yagpcc_control_service_proto_init() }
func file_api_proto_agent_segment_yagpcc_control_service_proto_init() {
	if File_api_proto_agent_segment_yagpcc_control_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_segment_yagpcc_control_service_proto_rawDesc), len(file_api_proto_agent_segment_yagpcc_control_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_segment_yagpcc_control_service_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_segment_yagpcc_control_service_proto_depIdxs,
		EnumInfos:         file_api_proto_agent_segment_yagpcc_control_service_proto_enumTypes,
		MessageInfos:      file_api_proto_agent_segment_yagpcc_control_service_proto_msgTypes,
	}.Build()
	File_api_proto_agent_segment_yagpcc_control_service_proto = out.File
	file_api_proto_agent_segment_yagpcc_control_service_proto_goTypes = nil
	file_api_proto_agent_segment_yagpcc_control_service_proto_depIdxs = nil
}
