// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed
// with this work for additional information regarding copyright
// ownership. The ASF licenses this file to You under the Apache
// License, Version 2.0 (the "License"); you may not use this file
// except in compliance with the License. You may obtain a copy of the
// License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

syntax = "proto3";

import "google/protobuf/timestamp.proto";

import "api/proto/common/yagpcc_metrics.proto";

package yagpcc;
option java_outer_classname = "SegmentYAGPCCAS";
option go_package = "github.com/open-gpdb/yagpcc/api/proto/agent_segment;greenplum";

service SetQueryInfo {
    rpc SetMetricQuery (SetQueryReq) returns (MetricResponse) {}
}

message MetricResponse {
    MetricResponseStatusCode error_code = 1;
    string error_text = 2;
}

enum MetricResponseStatusCode {
    METRIC_RESPONSE_STATUS_CODE_UNSPECIFIED = 0;
    METRIC_RESPONSE_STATUS_CODE_SUCCESS = 1;
    METRIC_RESPONSE_STATUS_CODE_ERROR = 2;
}

message SetQueryReq {
    QueryStatus           query_status    = 1;
    google.protobuf.Timestamp datetime    = 2;
    QueryKey                 query_key    = 3;
    SegmentKey             segment_key    = 4;
    QueryInfo               query_info    = 5;
    GPMetrics            query_metrics    = 6;
    google.protobuf.Timestamp submit_time = 8;
    google.protobuf.Timestamp start_time  = 9;
    google.protobuf.Timestamp end_time    = 10;
    AdditionalQueryInfo add_info          = 11;
}
