// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed
// with this work for additional information regarding copyright
// ownership. The ASF licenses this file to You under the Apache
// License, Version 2.0 (the "License"); you may not use this file
// except in compliance with the License. You may obtain a copy of the
// License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

syntax = "proto3";

import "google/protobuf/timestamp.proto";

package yagpcc;
option java_outer_classname = "SegmentYAGPCCAC";
option go_package = "github.com/open-gpdb/yagpcc/api/proto/agent_segment;greenplum";

service AgentControl {
    rpc ResetStat (ResetStatReq) returns (ControlResponse) {}

    rpc GetAgentInfo (GetInfoReq) returns (InfoRepsonse) {}
}

message ResetStatReq {    
}

message GetInfoReq {
}

message InfoRepsonse {
    string version = 1;

    google.protobuf.Timestamp reset_time = 2;
    uint64 queries_count = 3;
    uint64 plannodes_count = 4;
    uint64 queries_wiped_out = 5;
    uint64 plans_wiped_out = 6;
    uint64 num_gc = 7;
    uint64 heap_inuse = 8;
    uint64 heap_alloc = 9;
    uint32 num_sys_gc = 10;
}

message ControlResponse {
    ControlResponseStatusCode error_code = 1;
    string error_text = 2;
}

enum ControlResponseStatusCode {
    CONTROL_RESPONSE_STATUS_CODE_UNSPECIFIED = 0;
    CONTROL_RESPONSE_STATUS_CODE_SUCCESS = 1;
    CONTROL_RESPONSE_STATUS_CODE_ERROR = 2;
}

