// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed
// with this work for additional information regarding copyright
// ownership. The ASF licenses this file to You under the Apache
// License, Version 2.0 (the "License"); you may not use this file
// except in compliance with the License. You may obtain a copy of the
// License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/proto/agent_segment/yagpcc_get_service.proto

package greenplum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetQueryInfo_GetMetricQueries_FullMethodName = "/yagpcc.GetQueryInfo/GetMetricQueries"
	GetQueryInfo_GetPidProcStat_FullMethodName   = "/yagpcc.GetQueryInfo/GetPidProcStat"
	GetQueryInfo_GetHostStat_FullMethodName      = "/yagpcc.GetQueryInfo/GetHostStat"
)

// GetQueryInfoClient is the client API for GetQueryInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetQueryInfoClient interface {
	GetMetricQueries(ctx context.Context, in *GetQueriesInfoReq, opts ...grpc.CallOption) (*GetQueriesInfoResponse, error)
	GetPidProcStat(ctx context.Context, in *GetPidProcInfoReq, opts ...grpc.CallOption) (*GetPidProcInfoResponse, error)
	GetHostStat(ctx context.Context, in *GetHostStatReq, opts ...grpc.CallOption) (*GetHostStatResponse, error)
}

type getQueryInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewGetQueryInfoClient(cc grpc.ClientConnInterface) GetQueryInfoClient {
	return &getQueryInfoClient{cc}
}

func (c *getQueryInfoClient) GetMetricQueries(ctx context.Context, in *GetQueriesInfoReq, opts ...grpc.CallOption) (*GetQueriesInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueriesInfoResponse)
	err := c.cc.Invoke(ctx, GetQueryInfo_GetMetricQueries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getQueryInfoClient) GetPidProcStat(ctx context.Context, in *GetPidProcInfoReq, opts ...grpc.CallOption) (*GetPidProcInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPidProcInfoResponse)
	err := c.cc.Invoke(ctx, GetQueryInfo_GetPidProcStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getQueryInfoClient) GetHostStat(ctx context.Context, in *GetHostStatReq, opts ...grpc.CallOption) (*GetHostStatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostStatResponse)
	err := c.cc.Invoke(ctx, GetQueryInfo_GetHostStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetQueryInfoServer is the server API for GetQueryInfo service.
// All implementations must embed UnimplementedGetQueryInfoServer
// for forward compatibility.
type GetQueryInfoServer interface {
	GetMetricQueries(context.Context, *GetQueriesInfoReq) (*GetQueriesInfoResponse, error)
	GetPidProcStat(context.Context, *GetPidProcInfoReq) (*GetPidProcInfoResponse, error)
	GetHostStat(context.Context, *GetHostStatReq) (*GetHostStatResponse, error)
	mustEmbedUnimplementedGetQueryInfoServer()
}

// UnimplementedGetQueryInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetQueryInfoServer struct{}

func (UnimplementedGetQueryInfoServer) GetMetricQueries(context.Context, *GetQueriesInfoReq) (*GetQueriesInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetricQueries not implemented")
}
func (UnimplementedGetQueryInfoServer) GetPidProcStat(context.Context, *GetPidProcInfoReq) (*GetPidProcInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPidProcStat not implemented")
}
func (UnimplementedGetQueryInfoServer) GetHostStat(context.Context, *GetHostStatReq) (*GetHostStatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostStat not implemented")
}
func (UnimplementedGetQueryInfoServer) mustEmbedUnimplementedGetQueryInfoServer() {}
func (UnimplementedGetQueryInfoServer) testEmbeddedByValue()                      {}

// UnsafeGetQueryInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetQueryInfoServer will
// result in compilation errors.
type UnsafeGetQueryInfoServer interface {
	mustEmbedUnimplementedGetQueryInfoServer()
}

func RegisterGetQueryInfoServer(s grpc.ServiceRegistrar, srv GetQueryInfoServer) {
	// If the following call panics, it indicates UnimplementedGetQueryInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetQueryInfo_ServiceDesc, srv)
}

func _GetQueryInfo_GetMetricQueries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueriesInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetQueryInfoServer).GetMetricQueries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetQueryInfo_GetMetricQueries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetQueryInfoServer).GetMetricQueries(ctx, req.(*GetQueriesInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GetQueryInfo_GetPidProcStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPidProcInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetQueryInfoServer).GetPidProcStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetQueryInfo_GetPidProcStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetQueryInfoServer).GetPidProcStat(ctx, req.(*GetPidProcInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GetQueryInfo_GetHostStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostStatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetQueryInfoServer).GetHostStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetQueryInfo_GetHostStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetQueryInfoServer).GetHostStat(ctx, req.(*GetHostStatReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GetQueryInfo_ServiceDesc is the grpc.ServiceDesc for GetQueryInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetQueryInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yagpcc.GetQueryInfo",
	HandlerType: (*GetQueryInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetricQueries",
			Handler:    _GetQueryInfo_GetMetricQueries_Handler,
		},
		{
			MethodName: "GetPidProcStat",
			Handler:    _GetQueryInfo_GetPidProcStat_Handler,
		},
		{
			MethodName: "GetHostStat",
			Handler:    _GetQueryInfo_GetHostStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/agent_segment/yagpcc_get_service.proto",
}
