// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/agent_segment/yagpcc_set_service.proto

package greenplum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SetQueryInfo_SetMetricQuery_FullMethodName = "/yagpcc.SetQueryInfo/SetMetricQuery"
)

// SetQueryInfoClient is the client API for SetQueryInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SetQueryInfoClient interface {
	SetMetricQuery(ctx context.Context, in *SetQueryReq, opts ...grpc.CallOption) (*MetricResponse, error)
}

type setQueryInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewSetQueryInfoClient(cc grpc.ClientConnInterface) SetQueryInfoClient {
	return &setQueryInfoClient{cc}
}

func (c *setQueryInfoClient) SetMetricQuery(ctx context.Context, in *SetQueryReq, opts ...grpc.CallOption) (*MetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricResponse)
	err := c.cc.Invoke(ctx, SetQueryInfo_SetMetricQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetQueryInfoServer is the server API for SetQueryInfo service.
// All implementations must embed UnimplementedSetQueryInfoServer
// for forward compatibility.
type SetQueryInfoServer interface {
	SetMetricQuery(context.Context, *SetQueryReq) (*MetricResponse, error)
	mustEmbedUnimplementedSetQueryInfoServer()
}

// UnimplementedSetQueryInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSetQueryInfoServer struct{}

func (UnimplementedSetQueryInfoServer) SetMetricQuery(context.Context, *SetQueryReq) (*MetricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMetricQuery not implemented")
}
func (UnimplementedSetQueryInfoServer) mustEmbedUnimplementedSetQueryInfoServer() {}
func (UnimplementedSetQueryInfoServer) testEmbeddedByValue()                      {}

// UnsafeSetQueryInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SetQueryInfoServer will
// result in compilation errors.
type UnsafeSetQueryInfoServer interface {
	mustEmbedUnimplementedSetQueryInfoServer()
}

func RegisterSetQueryInfoServer(s grpc.ServiceRegistrar, srv SetQueryInfoServer) {
	// If the following call panics, it indicates UnimplementedSetQueryInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SetQueryInfo_ServiceDesc, srv)
}

func _SetQueryInfo_SetMetricQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetQueryInfoServer).SetMetricQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetQueryInfo_SetMetricQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetQueryInfoServer).SetMetricQuery(ctx, req.(*SetQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SetQueryInfo_ServiceDesc is the grpc.ServiceDesc for SetQueryInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SetQueryInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yagpcc.SetQueryInfo",
	HandlerType: (*SetQueryInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMetricQuery",
			Handler:    _SetQueryInfo_SetMetricQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/agent_segment/yagpcc_set_service.proto",
}
