// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed
// with this work for additional information regarding copyright
// ownership. The ASF licenses this file to You under the Apache
// License, Version 2.0 (the "License"); you may not use this file
// except in compliance with the License. You may obtain a copy of the
// License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/agent_segment/yagpcc_get_service.proto

package greenplum

import (
	common "github.com/open-gpdb/yagpcc/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHostStatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostStatReq) Reset() {
	*x = GetHostStatReq{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostStatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostStatReq) ProtoMessage() {}

func (x *GetHostStatReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostStatReq.ProtoReflect.Descriptor instead.
func (*GetHostStatReq) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{0}
}

type LoadAvg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avg1          float64                `protobuf:"fixed64,1,opt,name=avg1,proto3" json:"avg1,omitempty"`
	Avg5          float64                `protobuf:"fixed64,2,opt,name=avg5,proto3" json:"avg5,omitempty"`
	Avg15         float64                `protobuf:"fixed64,3,opt,name=avg15,proto3" json:"avg15,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAvg) Reset() {
	*x = LoadAvg{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAvg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAvg) ProtoMessage() {}

func (x *LoadAvg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAvg.ProtoReflect.Descriptor instead.
func (*LoadAvg) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoadAvg) GetAvg1() float64 {
	if x != nil {
		return x.Avg1
	}
	return 0
}

func (x *LoadAvg) GetAvg5() float64 {
	if x != nil {
		return x.Avg5
	}
	return 0
}

func (x *LoadAvg) GetAvg15() float64 {
	if x != nil {
		return x.Avg15
	}
	return 0
}

type CpuUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuUsage) Reset() {
	*x = CpuUsage{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuUsage) ProtoMessage() {}

func (x *CpuUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuUsage.ProtoReflect.Descriptor instead.
func (*CpuUsage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{2}
}

func (x *CpuUsage) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

type GetHostStatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// /proc/loadavg statistics
	LoadAvg *LoadAvg `protobuf:"bytes,1,opt,name=load_avg,json=loadAvg,proto3" json:"load_avg,omitempty"`
	// cpu usage
	CpuUsage      *CpuUsage `protobuf:"bytes,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostStatResponse) Reset() {
	*x = GetHostStatResponse{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostStatResponse) ProtoMessage() {}

func (x *GetHostStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostStatResponse.ProtoReflect.Descriptor instead.
func (*GetHostStatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetHostStatResponse) GetLoadAvg() *LoadAvg {
	if x != nil {
		return x.LoadAvg
	}
	return nil
}

func (x *GetHostStatResponse) GetCpuUsage() *CpuUsage {
	if x != nil {
		return x.CpuUsage
	}
	return nil
}

type QueryData struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	QueryStatus    common.QueryStatus          `protobuf:"varint,1,opt,name=query_status,json=queryStatus,proto3,enum=yagpcc.QueryStatus" json:"query_status,omitempty"`
	QueryStart     *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=query_start,json=queryStart,proto3" json:"query_start,omitempty"`
	QueryEnd       *timestamppb.Timestamp      `protobuf:"bytes,3,opt,name=query_end,json=queryEnd,proto3" json:"query_end,omitempty"`
	QueryKey       *common.QueryKey            `protobuf:"bytes,4,opt,name=query_key,json=queryKey,proto3" json:"query_key,omitempty"`
	SegmentKey     *common.SegmentKey          `protobuf:"bytes,5,opt,name=segment_key,json=segmentKey,proto3" json:"segment_key,omitempty"`
	QueryInfo      *common.QueryInfo           `protobuf:"bytes,6,opt,name=query_info,json=queryInfo,proto3" json:"query_info,omitempty"`
	QueryMetrics   *common.GPMetrics           `protobuf:"bytes,7,opt,name=query_metrics,json=queryMetrics,proto3" json:"query_metrics,omitempty"`
	AdditionalStat *common.AdditionalQueryStat `protobuf:"bytes,9,opt,name=additional_stat,json=additionalStat,proto3" json:"additional_stat,omitempty"`
	SliceId        int64                       `protobuf:"varint,10,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryData) Reset() {
	*x = QueryData{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryData) ProtoMessage() {}

func (x *QueryData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryData.ProtoReflect.Descriptor instead.
func (*QueryData) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{4}
}

func (x *QueryData) GetQueryStatus() common.QueryStatus {
	if x != nil {
		return x.QueryStatus
	}
	return common.QueryStatus(0)
}

func (x *QueryData) GetQueryStart() *timestamppb.Timestamp {
	if x != nil {
		return x.QueryStart
	}
	return nil
}

func (x *QueryData) GetQueryEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.QueryEnd
	}
	return nil
}

func (x *QueryData) GetQueryKey() *common.QueryKey {
	if x != nil {
		return x.QueryKey
	}
	return nil
}

func (x *QueryData) GetSegmentKey() *common.SegmentKey {
	if x != nil {
		return x.SegmentKey
	}
	return nil
}

func (x *QueryData) GetQueryInfo() *common.QueryInfo {
	if x != nil {
		return x.QueryInfo
	}
	return nil
}

func (x *QueryData) GetQueryMetrics() *common.GPMetrics {
	if x != nil {
		return x.QueryMetrics
	}
	return nil
}

func (x *QueryData) GetAdditionalStat() *common.AdditionalQueryStat {
	if x != nil {
		return x.AdditionalStat
	}
	return nil
}

func (x *QueryData) GetSliceId() int64 {
	if x != nil {
		return x.SliceId
	}
	return 0
}

type GetQueriesInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueriesData   []*QueryData           `protobuf:"bytes,1,rep,name=queries_data,json=queriesData,proto3" json:"queries_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueriesInfoResponse) Reset() {
	*x = GetQueriesInfoResponse{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueriesInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueriesInfoResponse) ProtoMessage() {}

func (x *GetQueriesInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueriesInfoResponse.ProtoReflect.Descriptor instead.
func (*GetQueriesInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetQueriesInfoResponse) GetQueriesData() []*QueryData {
	if x != nil {
		return x.QueriesData
	}
	return nil
}

type GetQueriesInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterQueries []*common.QueryKey     `protobuf:"bytes,1,rep,name=filter_queries,json=filterQueries,proto3" json:"filter_queries,omitempty"` // if set show queries with specific QueryKey's
	FromTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`                // if set filter out entries with query start before from_time
	ToTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`                      // if set filter out entries with query end after to_time
	ClearSent     bool                   `protobuf:"varint,4,opt,name=clear_sent,json=clearSent,proto3" json:"clear_sent,omitempty"`            // clear info after sent query data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueriesInfoReq) Reset() {
	*x = GetQueriesInfoReq{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueriesInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueriesInfoReq) ProtoMessage() {}

func (x *GetQueriesInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueriesInfoReq.ProtoReflect.Descriptor instead.
func (*GetQueriesInfoReq) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetQueriesInfoReq) GetFilterQueries() []*common.QueryKey {
	if x != nil {
		return x.FilterQueries
	}
	return nil
}

func (x *GetQueriesInfoReq) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *GetQueriesInfoReq) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

func (x *GetQueriesInfoReq) GetClearSent() bool {
	if x != nil {
		return x.ClearSent
	}
	return false
}

type GetPidProcInfoResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PidProcData   []*common.GpPidProcInfo `protobuf:"bytes,1,rep,name=pid_proc_data,json=pidProcData,proto3" json:"pid_proc_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPidProcInfoResponse) Reset() {
	*x = GetPidProcInfoResponse{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPidProcInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPidProcInfoResponse) ProtoMessage() {}

func (x *GetPidProcInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPidProcInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPidProcInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetPidProcInfoResponse) GetPidProcData() []*common.GpPidProcInfo {
	if x != nil {
		return x.PidProcData
	}
	return nil
}

type SegmentProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GpSegmentId   int64                  `protobuf:"varint,1,opt,name=gp_segment_id,json=gpSegmentId,proto3" json:"gp_segment_id,omitempty"`
	SessId        int64                  `protobuf:"varint,2,opt,name=sess_id,json=sessId,proto3" json:"sess_id,omitempty"`
	Pid           int64                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentProcess) Reset() {
	*x = SegmentProcess{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentProcess) ProtoMessage() {}

func (x *SegmentProcess) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentProcess.ProtoReflect.Descriptor instead.
func (*SegmentProcess) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{8}
}

func (x *SegmentProcess) GetGpSegmentId() int64 {
	if x != nil {
		return x.GpSegmentId
	}
	return 0
}

func (x *SegmentProcess) GetSessId() int64 {
	if x != nil {
		return x.SessId
	}
	return 0
}

func (x *SegmentProcess) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type GetPidProcInfoReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SegmentProcess []*SegmentProcess      `protobuf:"bytes,1,rep,name=segment_process,json=segmentProcess,proto3" json:"segment_process,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPidProcInfoReq) Reset() {
	*x = GetPidProcInfoReq{}
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPidProcInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPidProcInfoReq) ProtoMessage() {}

func (x *GetPidProcInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPidProcInfoReq.ProtoReflect.Descriptor instead.
func (*GetPidProcInfoReq) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetPidProcInfoReq) GetSegmentProcess() []*SegmentProcess {
	if x != nil {
		return x.SegmentProcess
	}
	return nil
}

var File_api_proto_agent_segment_yagpcc_get_service_proto protoreflect.FileDescriptor

const file_api_proto_agent_segment_yagpcc_get_service_proto_rawDesc = "" +
	"\n" +
	"0api/proto/agent_segment/yagpcc_get_service.proto\x12\x06yagpcc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%api/proto/common/yagpcc_metrics.proto\"\x10\n" +
	"\x0eGetHostStatReq\"G\n" +
	"\aLoadAvg\x12\x12\n" +
	"\x04avg1\x18\x01 \x01(\x01R\x04avg1\x12\x12\n" +
	"\x04avg5\x18\x02 \x01(\x01R\x04avg5\x12\x14\n" +
	"\x05avg15\x18\x03 \x01(\x01R\x05avg15\"'\n" +
	"\bCpuUsage\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\"p\n" +
	"\x13GetHostStatResponse\x12*\n" +
	"\bload_avg\x18\x01 \x01(\v2\x0f.yagpcc.LoadAvgR\aloadAvg\x12-\n" +
	"\tcpu_usage\x18\x02 \x01(\v2\x10.yagpcc.CpuUsageR\bcpuUsage\"\xe8\x03\n" +
	"\tQueryData\x126\n" +
	"\fquery_status\x18\x01 \x01(\x0e2\x13.yagpcc.QueryStatusR\vqueryStatus\x12;\n" +
	"\vquery_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"queryStart\x127\n" +
	"\tquery_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bqueryEnd\x12-\n" +
	"\tquery_key\x18\x04 \x01(\v2\x10.yagpcc.QueryKeyR\bqueryKey\x123\n" +
	"\vsegment_key\x18\x05 \x01(\v2\x12.yagpcc.SegmentKeyR\n" +
	"segmentKey\x120\n" +
	"\n" +
	"query_info\x18\x06 \x01(\v2\x11.yagpcc.QueryInfoR\tqueryInfo\x126\n" +
	"\rquery_metrics\x18\a \x01(\v2\x11.yagpcc.GPMetricsR\fqueryMetrics\x12D\n" +
	"\x0fadditional_stat\x18\t \x01(\v2\x1b.yagpcc.AdditionalQueryStatR\x0eadditionalStat\x12\x19\n" +
	"\bslice_id\x18\n" +
	" \x01(\x03R\asliceId\"N\n" +
	"\x16GetQueriesInfoResponse\x124\n" +
	"\fqueries_data\x18\x01 \x03(\v2\x11.yagpcc.QueryDataR\vqueriesData\"\xd9\x01\n" +
	"\x11GetQueriesInfoReq\x127\n" +
	"\x0efilter_queries\x18\x01 \x03(\v2\x10.yagpcc.QueryKeyR\rfilterQueries\x127\n" +
	"\tfrom_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bfromTime\x123\n" +
	"\ato_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06toTime\x12\x1d\n" +
	"\n" +
	"clear_sent\x18\x04 \x01(\bR\tclearSent\"S\n" +
	"\x16GetPidProcInfoResponse\x129\n" +
	"\rpid_proc_data\x18\x01 \x03(\v2\x15.yagpcc.GpPidProcInfoR\vpidProcData\"_\n" +
	"\x0eSegmentProcess\x12\"\n" +
	"\rgp_segment_id\x18\x01 \x01(\x03R\vgpSegmentId\x12\x17\n" +
	"\asess_id\x18\x02 \x01(\x03R\x06sessId\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x03R\x03pid\"T\n" +
	"\x11GetPidProcInfoReq\x12?\n" +
	"\x0fsegment_process\x18\x01 \x03(\v2\x16.yagpcc.SegmentProcessR\x0esegmentProcess2\xf4\x01\n" +
	"\fGetQueryInfo\x12O\n" +
	"\x10GetMetricQueries\x12\x19.yagpcc.GetQueriesInfoReq\x1a\x1e.yagpcc.GetQueriesInfoResponse\"\x00\x12M\n" +
	"\x0eGetPidProcStat\x12\x19.yagpcc.GetPidProcInfoReq\x1a\x1e.yagpcc.GetPidProcInfoResponse\"\x00\x12D\n" +
	"\vGetHostStat\x12\x16.yagpcc.GetHostStatReq\x1a\x1b.yagpcc.GetHostStatResponse\"\x00BPB\x0fSegmentYAGPCCAGZ=github.com/open-gpdb/yagpcc/api/proto/agent_segment;greenplumb\x06proto3"

var (
	file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescOnce sync.Once
	file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescData []byte
)

func file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescGZIP() []byte {
	file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_segment_yagpcc_get_service_proto_rawDesc), len(file_api_proto_agent_segment_yagpcc_get_service_proto_rawDesc)))
	})
	return file_api_proto_agent_segment_yagpcc_get_service_proto_rawDescData
}

var file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_agent_segment_yagpcc_get_service_proto_goTypes = []any{
	(*GetHostStatReq)(nil),             // 0: yagpcc.GetHostStatReq
	(*LoadAvg)(nil),                    // 1: yagpcc.LoadAvg
	(*CpuUsage)(nil),                   // 2: yagpcc.CpuUsage
	(*GetHostStatResponse)(nil),        // 3: yagpcc.GetHostStatResponse
	(*QueryData)(nil),                  // 4: yagpcc.QueryData
	(*GetQueriesInfoResponse)(nil),     // 5: yagpcc.GetQueriesInfoResponse
	(*GetQueriesInfoReq)(nil),          // 6: yagpcc.GetQueriesInfoReq
	(*GetPidProcInfoResponse)(nil),     // 7: yagpcc.GetPidProcInfoResponse
	(*SegmentProcess)(nil),             // 8: yagpcc.SegmentProcess
	(*GetPidProcInfoReq)(nil),          // 9: yagpcc.GetPidProcInfoReq
	(common.QueryStatus)(0),            // 10: yagpcc.QueryStatus
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
	(*common.QueryKey)(nil),            // 12: yagpcc.QueryKey
	(*common.SegmentKey)(nil),          // 13: yagpcc.SegmentKey
	(*common.QueryInfo)(nil),           // 14: yagpcc.QueryInfo
	(*common.GPMetrics)(nil),           // 15: yagpcc.GPMetrics
	(*common.AdditionalQueryStat)(nil), // 16: yagpcc.AdditionalQueryStat
	(*common.GpPidProcInfo)(nil),       // 17: yagpcc.GpPidProcInfo
}
var file_api_proto_agent_segment_yagpcc_get_service_proto_depIdxs = []int32{
	1,  // 0: yagpcc.GetHostStatResponse.load_avg:type_name -> yagpcc.LoadAvg
	2,  // 1: yagpcc.GetHostStatResponse.cpu_usage:type_name -> yagpcc.CpuUsage
	10, // 2: yagpcc.QueryData.query_status:type_name -> yagpcc.QueryStatus
	11, // 3: yagpcc.QueryData.query_start:type_name -> google.protobuf.Timestamp
	11, // 4: yagpcc.QueryData.query_end:type_name -> google.protobuf.Timestamp
	12, // 5: yagpcc.QueryData.query_key:type_name -> yagpcc.QueryKey
	13, // 6: yagpcc.QueryData.segment_key:type_name -> yagpcc.SegmentKey
	14, // 7: yagpcc.QueryData.query_info:type_name -> yagpcc.QueryInfo
	15, // 8: yagpcc.QueryData.query_metrics:type_name -> yagpcc.GPMetrics
	16, // 9: yagpcc.QueryData.additional_stat:type_name -> yagpcc.AdditionalQueryStat
	4,  // 10: yagpcc.GetQueriesInfoResponse.queries_data:type_name -> yagpcc.QueryData
	12, // 11: yagpcc.GetQueriesInfoReq.filter_queries:type_name -> yagpcc.QueryKey
	11, // 12: yagpcc.GetQueriesInfoReq.from_time:type_name -> google.protobuf.Timestamp
	11, // 13: yagpcc.GetQueriesInfoReq.to_time:type_name -> google.protobuf.Timestamp
	17, // 14: yagpcc.GetPidProcInfoResponse.pid_proc_data:type_name -> yagpcc.GpPidProcInfo
	8,  // 15: yagpcc.GetPidProcInfoReq.segment_process:type_name -> yagpcc.SegmentProcess
	6,  // 16: yagpcc.GetQueryInfo.GetMetricQueries:input_type -> yagpcc.GetQueriesInfoReq
	9,  // 17: yagpcc.GetQueryInfo.GetPidProcStat:input_type -> yagpcc.GetPidProcInfoReq
	0,  // 18: yagpcc.GetQueryInfo.GetHostStat:input_type -> yagpcc.GetHostStatReq
	5,  // 19: yagpcc.GetQueryInfo.GetMetricQueries:output_type -> yagpcc.GetQueriesInfoResponse
	7,  // 20: yagpcc.GetQueryInfo.GetPidProcStat:output_type -> yagpcc.GetPidProcInfoResponse
	3,  // 21: yagpcc.GetQueryInfo.GetHostStat:output_type -> yagpcc.GetHostStatResponse
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_agent_segment_yagpcc_get_service_proto_init() }
func file_api_proto_agent_segment_yagpcc_get_service_proto_init() {
	if File_api_proto_agent_segment_yagpcc_get_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_segment_yagpcc_get_service_proto_rawDesc), len(file_api_proto_agent_segment_yagpcc_get_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_segment_yagpcc_get_service_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_segment_yagpcc_get_service_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_segment_yagpcc_get_service_proto_msgTypes,
	}.Build()
	File_api_proto_agent_segment_yagpcc_get_service_proto = out.File
	file_api_proto_agent_segment_yagpcc_get_service_proto_goTypes = nil
	file_api_proto_agent_segment_yagpcc_get_service_proto_depIdxs = nil
}
