// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/agent_segment/yagpcc_set_service.proto

package greenplum

import (
	common "github.com/open-gpdb/yagpcc/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricResponseStatusCode int32

const (
	MetricResponseStatusCode_METRIC_RESPONSE_STATUS_CODE_UNSPECIFIED MetricResponseStatusCode = 0
	MetricResponseStatusCode_METRIC_RESPONSE_STATUS_CODE_SUCCESS     MetricResponseStatusCode = 1
	MetricResponseStatusCode_METRIC_RESPONSE_STATUS_CODE_ERROR       MetricResponseStatusCode = 2
)

// Enum value maps for MetricResponseStatusCode.
var (
	MetricResponseStatusCode_name = map[int32]string{
		0: "METRIC_RESPONSE_STATUS_CODE_UNSPECIFIED",
		1: "METRIC_RESPONSE_STATUS_CODE_SUCCESS",
		2: "METRIC_RESPONSE_STATUS_CODE_ERROR",
	}
	MetricResponseStatusCode_value = map[string]int32{
		"METRIC_RESPONSE_STATUS_CODE_UNSPECIFIED": 0,
		"METRIC_RESPONSE_STATUS_CODE_SUCCESS":     1,
		"METRIC_RESPONSE_STATUS_CODE_ERROR":       2,
	}
)

func (x MetricResponseStatusCode) Enum() *MetricResponseStatusCode {
	p := new(MetricResponseStatusCode)
	*p = x
	return p
}

func (x MetricResponseStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricResponseStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_agent_segment_yagpcc_set_service_proto_enumTypes[0].Descriptor()
}

func (MetricResponseStatusCode) Type() protoreflect.EnumType {
	return &file_api_proto_agent_segment_yagpcc_set_service_proto_enumTypes[0]
}

func (x MetricResponseStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricResponseStatusCode.Descriptor instead.
func (MetricResponseStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_set_service_proto_rawDescGZIP(), []int{0}
}

type MetricResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ErrorCode     MetricResponseStatusCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=yagpcc.MetricResponseStatusCode" json:"error_code,omitempty"`
	ErrorText     string                   `protobuf:"bytes,2,opt,name=error_text,json=errorText,proto3" json:"error_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_api_proto_agent_segment_yagpcc_set_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_set_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_set_service_proto_rawDescGZIP(), []int{0}
}

func (x *MetricResponse) GetErrorCode() MetricResponseStatusCode {
	if x != nil {
		return x.ErrorCode
	}
	return MetricResponseStatusCode_METRIC_RESPONSE_STATUS_CODE_UNSPECIFIED
}

func (x *MetricResponse) GetErrorText() string {
	if x != nil {
		return x.ErrorText
	}
	return ""
}

type SetQueryReq struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	QueryStatus   common.QueryStatus          `protobuf:"varint,1,opt,name=query_status,json=queryStatus,proto3,enum=yagpcc.QueryStatus" json:"query_status,omitempty"`
	Datetime      *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`
	QueryKey      *common.QueryKey            `protobuf:"bytes,3,opt,name=query_key,json=queryKey,proto3" json:"query_key,omitempty"`
	SegmentKey    *common.SegmentKey          `protobuf:"bytes,4,opt,name=segment_key,json=segmentKey,proto3" json:"segment_key,omitempty"`
	QueryInfo     *common.QueryInfo           `protobuf:"bytes,5,opt,name=query_info,json=queryInfo,proto3" json:"query_info,omitempty"`
	QueryMetrics  *common.GPMetrics           `protobuf:"bytes,6,opt,name=query_metrics,json=queryMetrics,proto3" json:"query_metrics,omitempty"`
	SubmitTime    *timestamppb.Timestamp      `protobuf:"bytes,8,opt,name=submit_time,json=submitTime,proto3" json:"submit_time,omitempty"`
	StartTime     *timestamppb.Timestamp      `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp      `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	AddInfo       *common.AdditionalQueryInfo `protobuf:"bytes,11,opt,name=add_info,json=addInfo,proto3" json:"add_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetQueryReq) Reset() {
	*x = SetQueryReq{}
	mi := &file_api_proto_agent_segment_yagpcc_set_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQueryReq) ProtoMessage() {}

func (x *SetQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_segment_yagpcc_set_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQueryReq.ProtoReflect.Descriptor instead.
func (*SetQueryReq) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_segment_yagpcc_set_service_proto_rawDescGZIP(), []int{1}
}

func (x *SetQueryReq) GetQueryStatus() common.QueryStatus {
	if x != nil {
		return x.QueryStatus
	}
	return common.QueryStatus(0)
}

func (x *SetQueryReq) GetDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

func (x *SetQueryReq) GetQueryKey() *common.QueryKey {
	if x != nil {
		return x.QueryKey
	}
	return nil
}

func (x *SetQueryReq) GetSegmentKey() *common.SegmentKey {
	if x != nil {
		return x.SegmentKey
	}
	return nil
}

func (x *SetQueryReq) GetQueryInfo() *common.QueryInfo {
	if x != nil {
		return x.QueryInfo
	}
	return nil
}

func (x *SetQueryReq) GetQueryMetrics() *common.GPMetrics {
	if x != nil {
		return x.QueryMetrics
	}
	return nil
}

func (x *SetQueryReq) GetSubmitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmitTime
	}
	return nil
}

func (x *SetQueryReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SetQueryReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *SetQueryReq) GetAddInfo() *common.AdditionalQueryInfo {
	if x != nil {
		return x.AddInfo
	}
	return nil
}

var File_api_proto_agent_segment_yagpcc_set_service_proto protoreflect.FileDescriptor

const file_api_proto_agent_segment_yagpcc_set_service_proto_rawDesc = "" +
	"\n" +
	"0api/proto/agent_segment/yagpcc_set_service.proto\x12\x06yagpcc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%api/proto/common/yagpcc_metrics.proto\"p\n" +
	"\x0eMetricResponse\x12?\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2 .yagpcc.MetricResponseStatusCodeR\terrorCode\x12\x1d\n" +
	"\n" +
	"error_text\x18\x02 \x01(\tR\terrorText\"\xb2\x04\n" +
	"\vSetQueryReq\x126\n" +
	"\fquery_status\x18\x01 \x01(\x0e2\x13.yagpcc.QueryStatusR\vqueryStatus\x126\n" +
	"\bdatetime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdatetime\x12-\n" +
	"\tquery_key\x18\x03 \x01(\v2\x10.yagpcc.QueryKeyR\bqueryKey\x123\n" +
	"\vsegment_key\x18\x04 \x01(\v2\x12.yagpcc.SegmentKeyR\n" +
	"segmentKey\x120\n" +
	"\n" +
	"query_info\x18\x05 \x01(\v2\x11.yagpcc.QueryInfoR\tqueryInfo\x126\n" +
	"\rquery_metrics\x18\x06 \x01(\v2\x11.yagpcc.GPMetricsR\fqueryMetrics\x12;\n" +
	"\vsubmit_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"submitTime\x129\n" +
	"\n" +
	"start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x126\n" +
	"\badd_info\x18\v \x01(\v2\x1b.yagpcc.AdditionalQueryInfoR\aaddInfo*\x97\x01\n" +
	"\x18MetricResponseStatusCode\x12+\n" +
	"'METRIC_RESPONSE_STATUS_CODE_UNSPECIFIED\x10\x00\x12'\n" +
	"#METRIC_RESPONSE_STATUS_CODE_SUCCESS\x10\x01\x12%\n" +
	"!METRIC_RESPONSE_STATUS_CODE_ERROR\x10\x022O\n" +
	"\fSetQueryInfo\x12?\n" +
	"\x0eSetMetricQuery\x12\x13.yagpcc.SetQueryReq\x1a\x16.yagpcc.MetricResponse\"\x00BPB\x0fSegmentYAGPCCASZ=github.com/open-gpdb/yagpcc/api/proto/agent_segment;greenplumb\x06proto3"

var (
	file_api_proto_agent_segment_yagpcc_set_service_proto_rawDescOnce sync.Once
	file_api_proto_agent_segment_yagpcc_set_service_proto_rawDescData []byte
)

func file_api_proto_agent_segment_yagpcc_set_service_proto_rawDescGZIP() []byte {
	file_api_proto_agent_segment_yagpcc_set_service_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_segment_yagpcc_set_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_segment_yagpcc_set_service_proto_rawDesc), len(file_api_proto_agent_segment_yagpcc_set_service_proto_rawDesc)))
	})
	return file_api_proto_agent_segment_yagpcc_set_service_proto_rawDescData
}

var file_api_proto_agent_segment_yagpcc_set_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_agent_segment_yagpcc_set_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_agent_segment_yagpcc_set_service_proto_goTypes = []any{
	(MetricResponseStatusCode)(0),      // 0: yagpcc.MetricResponseStatusCode
	(*MetricResponse)(nil),             // 1: yagpcc.MetricResponse
	(*SetQueryReq)(nil),                // 2: yagpcc.SetQueryReq
	(common.QueryStatus)(0),            // 3: yagpcc.QueryStatus
	(*timestamppb.Timestamp)(nil),      // 4: google.protobuf.Timestamp
	(*common.QueryKey)(nil),            // 5: yagpcc.QueryKey
	(*common.SegmentKey)(nil),          // 6: yagpcc.SegmentKey
	(*common.QueryInfo)(nil),           // 7: yagpcc.QueryInfo
	(*common.GPMetrics)(nil),           // 8: yagpcc.GPMetrics
	(*common.AdditionalQueryInfo)(nil), // 9: yagpcc.AdditionalQueryInfo
}
var file_api_proto_agent_segment_yagpcc_set_service_proto_depIdxs = []int32{
	0,  // 0: yagpcc.MetricResponse.error_code:type_name -> yagpcc.MetricResponseStatusCode
	3,  // 1: yagpcc.SetQueryReq.query_status:type_name -> yagpcc.QueryStatus
	4,  // 2: yagpcc.SetQueryReq.datetime:type_name -> google.protobuf.Timestamp
	5,  // 3: yagpcc.SetQueryReq.query_key:type_name -> yagpcc.QueryKey
	6,  // 4: yagpcc.SetQueryReq.segment_key:type_name -> yagpcc.SegmentKey
	7,  // 5: yagpcc.SetQueryReq.query_info:type_name -> yagpcc.QueryInfo
	8,  // 6: yagpcc.SetQueryReq.query_metrics:type_name -> yagpcc.GPMetrics
	4,  // 7: yagpcc.SetQueryReq.submit_time:type_name -> google.protobuf.Timestamp
	4,  // 8: yagpcc.SetQueryReq.start_time:type_name -> google.protobuf.Timestamp
	4,  // 9: yagpcc.SetQueryReq.end_time:type_name -> google.protobuf.Timestamp
	9,  // 10: yagpcc.SetQueryReq.add_info:type_name -> yagpcc.AdditionalQueryInfo
	2,  // 11: yagpcc.SetQueryInfo.SetMetricQuery:input_type -> yagpcc.SetQueryReq
	1,  // 12: yagpcc.SetQueryInfo.SetMetricQuery:output_type -> yagpcc.MetricResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_agent_segment_yagpcc_set_service_proto_init() }
func file_api_proto_agent_segment_yagpcc_set_service_proto_init() {
	if File_api_proto_agent_segment_yagpcc_set_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_segment_yagpcc_set_service_proto_rawDesc), len(file_api_proto_agent_segment_yagpcc_set_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_segment_yagpcc_set_service_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_segment_yagpcc_set_service_proto_depIdxs,
		EnumInfos:         file_api_proto_agent_segment_yagpcc_set_service_proto_enumTypes,
		MessageInfos:      file_api_proto_agent_segment_yagpcc_set_service_proto_msgTypes,
	}.Build()
	File_api_proto_agent_segment_yagpcc_set_service_proto = out.File
	file_api_proto_agent_segment_yagpcc_set_service_proto_goTypes = nil
	file_api_proto_agent_segment_yagpcc_set_service_proto_depIdxs = nil
}
