// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed
// with this work for additional information regarding copyright
// ownership. The ASF licenses this file to You under the Apache
// License, Version 2.0 (the "License"); you may not use this file
// except in compliance with the License. You may obtain a copy of the
// License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

syntax = "proto3";

import "google/protobuf/timestamp.proto";

import "api/proto/common/yagpcc_metrics.proto";

package yagpcc;
option java_outer_classname = "SegmentYAGPCCAG";
option go_package = "github.com/open-gpdb/yagpcc/api/proto/agent_segment;greenplum";

service GetQueryInfo {
    rpc GetMetricQueries (GetQueriesInfoReq) returns (GetQueriesInfoResponse) {}
    rpc GetPidProcStat (GetPidProcInfoReq) returns (GetPidProcInfoResponse) {}
    rpc GetHostStat (GetHostStatReq) returns (GetHostStatResponse) {}
}

message GetHostStatReq {
}

message LoadAvg {
 double avg1  = 1;
 double avg5  = 2;
 double avg15 = 3; 
}

message CpuUsage {
    double cpu_usage = 1;
}

message GetHostStatResponse {

    // /proc/loadavg statistics
    LoadAvg load_avg = 1;

    // cpu usage
    CpuUsage cpu_usage = 2;
}    

message QueryData {
    QueryStatus query_status              = 1;
    google.protobuf.Timestamp query_start = 2;
    google.protobuf.Timestamp query_end   = 3;
    QueryKey query_key                    = 4;
    SegmentKey segment_key                = 5;
    QueryInfo query_info                  = 6;
    GPMetrics query_metrics               = 7;
    AdditionalQueryStat additional_stat   = 9;
    int64 slice_id                        = 10;
}

message GetQueriesInfoResponse {
    repeated QueryData queries_data = 1; 
}

message GetQueriesInfoReq {
    repeated QueryKey filter_queries        = 1; // if set show queries with specific QueryKey's
    google.protobuf.Timestamp from_time     = 2; // if set filter out entries with query start before from_time
    google.protobuf.Timestamp to_time       = 3; // if set filter out entries with query end after to_time
    bool clear_sent                         = 4; // clear info after sent query data
}

message GetPidProcInfoResponse {
    repeated GpPidProcInfo pid_proc_data = 1;
}

message SegmentProcess {
    int64 gp_segment_id   = 1;
    int64 sess_id         = 2;
    int64 pid             = 3;
}

message GetPidProcInfoReq {
    repeated SegmentProcess segment_process = 1;
}
